#!/bin/bash

# Installs/configures the packages used in all images
# and creates the pootle user

set -e

apt-get update -qq
apt-get install \
   -y \
   -qq \
   --no-install-recommends \
     curl \
     git \
     locales \
     python-pip \
     sudo
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
rm -rf /var/cache/apt/archives
echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
locale-gen
update-locale LANG=en_US.UTF-8
pip install --no-cache-dir -q virtualenv
groupadd -r pootle
useradd \
    -m \
    -d /home/pootle \
    -k /etc/skel \
    -s /bin/bash \
    -g pootle \
  pootle
