#!/bin/bash

set -e

if [ ! -z "$BASE_INSTALL_PRE" ];
 then
     $BASE_INSTALL_PRE;
fi


if [ ! -z "$BASE_INSTALL_PKGS" ]; then
    apt-get update -qq
    apt-get install \
            -y -qq \
            --no-install-recommends \
            $BASE_INSTALL_PKGS
    apt-get clean
    rm -rf /var/lib/apt/lists/* /var/tmp/*
fi
