# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-30 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import pootle_project.models


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_project', '0010_add_reserved_code_validator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='checkstyle',
            field=models.CharField(default='standard', max_length=50, validators=[pootle_project.models.validate_project_checker], verbose_name='Quality Checks'),
        ),
    ]
