# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-06 13:51
from __future__ import unicode_literals

from django.db import migrations

def set_pootle_fs_style(apps, schema_editor):
    Project = apps.get_model('pootle_project', 'Project')
    for project in Project.objects.filter(treestyle='none'):
        project.treestyle = 'pootle_fs'
        project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_project', '0011_add_project_checker_validator'),
    ]

    operations = [
        migrations.RunPython(set_pootle_fs_style),
    ]
