# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-14 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_project', '0013_rename_treestyle_choice_to_pootle_fs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='treestyle',
            field=models.CharField(choices=[('auto', 'Automatic detection of gnu/non-gnu file layouts (slower)'), ('gnu', 'GNU style: files named by language code'), ('nongnu', 'Non-GNU: Each language in its own directory'), ('pootle_fs', 'Allow Pootle FS to manage filesystems')], default='auto', max_length=20, verbose_name='Project Tree Style'),
        ),
    ]
