# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-28 06:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_project', '0016_change_treestyle_choices_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='treestyle',
        ),
    ]
