# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-04 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_store', '0021_set_tp_path'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='store',
            unique_together=set([('obsolete', 'translation_project', 'tp_path'), ('parent', 'name')]),
        ),
    ]
