# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-05 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_store', '0022_add_unique_tp_path_idx'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together=set([('store', 'state', 'index', 'unitid_hash'), ('store', 'unitid_hash')]),
        ),
        migrations.AlterIndexTogether(
            name='store',
            index_together=set([('translation_project', 'pootle_path', 'is_template', 'filetype'), ('translation_project', 'is_template')]),
        ),
        migrations.AlterIndexTogether(
            name='unit',
            index_together=set([('store', 'revision'), ('store', 'index'), ('store', 'state'), ('store', 'mtime')]),
        ),
    ]
