# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-11 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_store', '0023_add_unit_store_idxs'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='tp_path',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Path'),
        ),
    ]
