# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_store', '0023_add_unit_store_idxs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'base_manager_name': 'objects', 'ordering': ['pootle_path']},
        ),
    ]
