# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-11 03:30
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import F

import logging
logger = logging.getLogger(__name__)


def set_unit_tp_path(apps, schema_editor):
    stores = apps.get_model("pootle_store.Store").objects.all()

    for store in stores:
        store.unit_set.all().update(tp_path=store.tp_path)
        logger.debug("Updated store: %s" % store.pootle_path)

class Migration(migrations.Migration):

    dependencies = [
        ('pootle_store', '0024_unit_tp_path'),
    ]

    operations = [
        migrations.RunPython(set_unit_tp_path),
    ]
