# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 14:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models

import pootle.core.user


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_store', '0024_set_store_base_manager_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='commented_by',
            field=models.ForeignKey(null=True, on_delete=models.SET(pootle.core.user.get_system_user), related_name='commented', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unit',
            name='reviewed_by',
            field=models.ForeignKey(null=True, on_delete=models.SET(pootle.core.user.get_system_user), related_name='reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unit',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=models.SET(pootle.core.user.get_system_user), related_name='submitted', to=settings.AUTH_USER_MODEL),
        ),
    ]
