# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 15:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import pootle.core.user


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_store', '0025_unit_on_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=models.SET(pootle.core.user.get_system_user), related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(pootle.core.user.get_system_user), related_name='suggestions', to=settings.AUTH_USER_MODEL),
        ),
    ]
