# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_store', '0027_unit_created_by'),
    ]

    operations = [
    ]
