# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_store', '0027_unit_created_by_squashed_0055_fill_unit_source_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitsource',
            name='creation_revision',
            field=models.IntegerField(blank=True, db_index=True, default=0),
        ),
    ]
