# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_store', '0028_set_created_by'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='unit',
            table='pootle_store_unit',
        ),
    ]
