# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_store', '0029_unit_tablename'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='store',
            table='pootle_store_store',
        ),
    ]
