# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-02 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_store', '0029_set_unit_creation_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='parent',
            field=models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='child_stores', to='pootle_app.Directory'),
        ),
        migrations.AlterField(
            model_name='store',
            name='translation_project',
            field=models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='pootle_translationproject.TranslationProject'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='store',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='pootle_store.Store'),
        ),
        migrations.AlterIndexTogether(
            name='unit',
            index_together=set([('store', 'revision'), ('store', 'index'), ('store', 'mtime')]),
        ),
    ]
