# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-04 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_store', '0030_remove_extra_indeces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='translator_comment_f',
        ),
    ]
