# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_store', '0031_suggestion_tablename'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='qualitycheck',
            table='pootle_store_qualitycheck',
        ),
    ]
