# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-10 18:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_store', '0033_remove_store_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualitycheck',
            name='message',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(4096)]),
        ),
        migrations.AlterField(
            model_name='unit',
            name='context',
            field=models.TextField(editable=False, null=True, validators=[django.core.validators.MaxLengthValidator(4096)]),
        ),
        migrations.AlterField(
            model_name='unit',
            name='developer_comment',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(4096)]),
        ),
        migrations.AlterField(
            model_name='unit',
            name='locations',
            field=models.TextField(editable=False, null=True, validators=[django.core.validators.MaxLengthValidator(4096)]),
        ),
        migrations.AlterField(
            model_name='unit',
            name='translator_comment',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(4096)]),
        ),
    ]
