# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_store', '0036_unitchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitsource',
            name='source_hash',
            field=models.CharField(editable=False, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='unitsource',
            name='source_length',
            field=models.SmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='unitsource',
            name='source_wordcount',
            field=models.SmallIntegerField(default=0, editable=False),
        ),
    ]
