# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_store', '0037_unitsource_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='tmp_state',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16),
        ),
    ]
