# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_store', '0037_set_unit_changed_with'),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name='unit',
        #    name='commented_by',
        #),
        migrations.RemoveField(
            model_name='unit',
            name='commented_on',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='reviewed_on',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='submitted_on',
        ),
    ]
