# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_store', '0040_remove_suggestion_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=16)),
            ],
            options={
                'abstract': False,
                'db_table': 'pootle_store_suggestion_state',
            },
        ),
    ]
