# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 05:40
from __future__ import unicode_literals

from django.db import migrations


def add_default_suggestion_states(apps, schema_editor):
    states = apps.get_model("pootle_store.SuggestionState").objects
    for state in ["pending", "accepted", "rejected"]:
        states.create(name=state)


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_store', '0041_suggestionstate'),
    ]

    operations = [
        migrations.RunPython(add_default_suggestion_states),
    ]
