# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_store', '0045_remove_suggestion_tmp_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitsource',
            name='unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unit_source', to='pootle_store.Unit'),
        ),
    ]
