# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 00:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_store', '0046_unit_source_one_to_one'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='source_hash',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='source_length',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='source_wordcount',
        ),
    ]
