# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 14:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import pootle.core.user


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_store', '0048_set_change_commented'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='commented_by',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='commented_on',
        ),
        migrations.AlterField(
            model_name='unitchange',
            name='commented_by',
            field=models.ForeignKey(null=True, on_delete=models.SET(pootle.core.user.get_system_user), related_name='commented', to=settings.AUTH_USER_MODEL),
        ),
    ]
