# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 19:06
from __future__ import unicode_literals

import logging
import time

from django.db import migrations

from pootle.core.user import get_system_user_id
from pootle_statistics.models import SubmissionTypes


logger = logging.getLogger(__name__)


def _update_reviewed(qs, unit_changes):
    values = qs.values_list("change", "reviewed_on", "reviewed_by")
    for change, reviewed_on, reviewed_by in values.iterator():
        unit_changes.filter(pk=change).update(
            reviewed_on=reviewed_on,
            reviewed_by=reviewed_by)


def _add_reviewed(qs, unit_changes):
    values = qs.values_list("id", "reviewed_on", "reviewed_by")
    total = values.count()
    offset = 0
    step = 10000
    start = time.time()
    while True:
        unit_changes.bulk_create(
            unit_changes.model(
                unit_id=unit,
                changed_with=(
                    SubmissionTypes.SYSTEM
                    if user == get_system_user_id()
                    else SubmissionTypes.WEB),
                reviewed_by_id=user,
                reviewed_on=timestamp)
            for unit, timestamp, user
            in values[offset: offset + step].iterator())
        logger.debug(
            "added %s/%s in %s seconds"
            % (offset + step, total, (time.time() - start)))
        if offset > total:
            break
        offset = offset + step


def set_change_reviewed(apps, schema_editor):
    units = apps.get_model("pootle_store.Unit").objects.all()
    unit_changes = apps.get_model("pootle_store.UnitChange").objects.all()
    _update_reviewed(
        units.filter(
            change__isnull=False).filter(reviewed_by__isnull=False),
        unit_changes)
    _add_reviewed(
        units.filter(
            change__isnull=True).filter(reviewed_by__isnull=False),
        unit_changes)


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_store', '0049_remove_unit_commented'),
    ]

    operations = [
        migrations.RunPython(set_change_reviewed),
    ]
