# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 09:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import pootle.core.user


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_store', '0052_set_change_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='submitted_on',
        ),
        migrations.AlterField(
            model_name='unitchange',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=models.SET(pootle.core.user.get_system_user), related_name='submitted', to=settings.AUTH_USER_MODEL),
        ),
    ]
