#!/bin/bash

set -e

if [ ! -z "$BASE_INSTALL_PRE" ];
 then
     $BASE_INSTALL_PRE;
fi

mv /tmp/build/entrypoint.sh /usr/local/bin/entrypoint.sh

apt-get update -qq
apt-get install \
   -y -qq \
   --no-install-recommends \
         gettext \
         gosu \
         make \
         python-pip \
         $BASE_INSTALL_PKGS
apt-get clean
rm -rf /var/lib/apt/lists/* /var/tmp/*
