#!/bin/bash

set -e

DOCKER_DIR=/home/pootle/pootle_env/src/pootle/docker

if [ $BUILD_IMAGE = production ]; then
    mv /tmp/build/wsgi /home/pootle/pootle_env/wsgi
fi

if [ ! -d "$DOCKER_DIR" ]; then
    mkdir -p /home/pootle/pootle_env/src/pootle/docker/
    mv /tmp/build/bin $DOCKER_DIR/bin
fi
