#!/usr/bin/env python

import sys
import os

scriptname = os.path.abspath(sys.argv[0])
translatedir = os.path.dirname(scriptname)
pythonpathstr = []
pathstr = []
for translatesubdir in ("convert", "tools", "filters", "services"):
  pathstr.append('"%s"' % os.path.join(translatedir, "translate", translatesubdir))
pathstr.append('"%s"' % os.path.join(translatedir, "tools"))
pathstr.append('"%s"' % os.path.join(translatedir, "Pootle"))
pathstr.append('"%s"' % os.path.join(translatedir, "Pootle", "tools"))
pathstr.append('"%s"' % os.path.join(translatedir, "virtaal", "bin"))
pathstr.append('"$PATH"')
pythonpathstr.append('"%s"' % translatedir)
pythonpathstr.append('"%s"' % os.path.join(translatedir, "virtaal"))
pythonpathstr.append('"%s"' % os.path.join(translatedir, "Pootle", "local_apps"))
pythonpathstr.append('"$PYTHONPATH"')

setpathfile = open(os.path.join(translatedir, "setpath"), "w")
setpathfile.write("#!/bin/bash\n")
setpathfile.write("#Running this script won't work. Use\n")
setpathfile.write("#	source setpath\n")
setpathfile.write("#or\n")
setpathfile.write("#	. setpath\n")
setpathfile.write("export PYTHONPATH=%s\n" % ":".join(pythonpathstr))
setpathfile.write("export PATH=%s\n" % ":".join(pathstr))
setpathfile.close()

os.chmod(os.path.join(translatedir, "setpath"), 0755)

