# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-19 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualfolder', '0015_vfdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vfdata',
            name='last_updated_unit',
        ),
    ]
