# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-06 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualfolder', '0016_remove_vfdata_last_updated_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vfdata',
            name='last_created_unit',
        ),
        migrations.RemoveField(
            model_name='vfdata',
            name='last_submission',
        ),
        migrations.RemoveField(
            model_name='vfdata',
            name='vf',
        ),
        migrations.DeleteModel(
            name='VFData',
        ),
    ]
