# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualfolder', '0018_rm_vfti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualfolder',
            name='filter_rules',
            field=models.TextField(help_text='Filtering rules that tell which files this virtual folder comprises.', verbose_name='Filter'),
        ),
    ]
