# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pootle_language', '0003_ensure_unique_special_chars'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=255)),
                ('fullname', models.CharField(db_index=True, max_length=255)),
                ('languages', models.ManyToManyField(to='pootle_language.Language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RemoteSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('type', models.CharField(max_length=32)),
                ('sync_frequency', models.IntegerField()),
                ('last_sync', models.DateTimeField()),
                ('update_frequency', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='remoteproject',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pootle_remote.RemoteSite'),
        ),
    ]
