#!/bin/bash

set -e

apt-get update -qq
apt-get install -y -qq \
         build-essential \
         libjpeg62-turbo-dev \
         libfreetype6-dev \
         liblcms2-dev \
         libtiff5-dev \
         libwebp-dev \
         libxml2-dev \
         libxslt-dev \
         python-dev \
         zlib1g-dev
rm -rf /var/lib/apt/lists/* /var/tmp/*
