# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-23 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_app', '0009_set_default_directory_pootle_path'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='directory',
            index_together=set([('obsolete', 'pootle_path')]),
        ),
    ]
