# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-23 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_statistics', '0004_fill_translated_wordcount'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='submission',
            index_together=set([('submitter', 'creation_time', 'id')]),
        ),
    ]
