# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_statistics', '0005_index_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'base_manager_name': 'objects', 'get_latest_by': 'creation_time', 'ordering': ['creation_time', 'pk']},
        ),
    ]
