# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 15:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import pootle.core.user


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_statistics', '0009_rm_similarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submitter',
            field=models.ForeignKey(null=True, on_delete=models.SET(pootle.core.user.get_system_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
