# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-17 12:21
from __future__ import unicode_literals

from django.db import migrations


def drop_scorelog_ctype(apps, schema_editor):
    ContentType = apps.get_model('contenttypes.ContentType')
    ContentType.objects.filter(app_label='pootle_statistics',
                               model='scorelog').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_statistics', '0011_cleanup_submissions_squashed_0023_remove_scorelog'),
    ]

    operations = [
        migrations.RunPython(drop_scorelog_ctype),
    ]
