# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-02 16:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import pootle.core.user


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pootle_statistics', '0012_drop_stale_scorelog_ctype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submitter',
            field=models.ForeignKey(db_index=False, null=True, on_delete=models.SET(pootle.core.user.get_system_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterIndexTogether(
            name='submission',
            index_together=set([('submitter', 'creation_time')]),
        ),
    ]
