# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_statistics', '0013_remove_revert_flag'),
    ]

    operations = [
    ]
