# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 15:53
from __future__ import unicode_literals

from django.db import migrations

# this was/is the value of SubmissionTypes.SOURCE
SOURCE_FLAG = 1


def truncate_source_field(apps, schema_editor):
    subs = apps.get_model("pootle_statistics.Submission").objects.all()
    subs.filter(field=SOURCE_FLAG).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_statistics', '0013_remove_revert_flag'),
    ]

    operations = [
        migrations.RunPython(truncate_source_field),
    ]
