# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-06 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_statistics', '0013_remove_extra_indeces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pootle_store.Unit'),
        ),
    ]
