# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_statistics', '0015_remove_system_scorelogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='action',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
