# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_statistics', '0018_remove_submission_store'),
        ('pootle_store', '0045_remove_suggestion_tmp_state'),
    ]

    operations = [
    ]
