# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_statistics', '0020_convert_checks_subs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorelog',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='scorelog',
            name='review_rate',
        ),
    ]
