# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_statistics', '0021_remove_paid_rates'),
    ]

    operations = [
    ]
