# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-12 20:51
from __future__ import unicode_literals

from django.db import migrations


SUGG_ACC_FLAG = 3


def drop_accept_suggestion_subs(apps, schema_editor):
    subs = apps.get_model("pootle_statistics.Submission").objects.all()
    subs.filter(type=SUGG_ACC_FLAG).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_statistics', '0023_remove_scorelog'),
    ]

    operations = [
        migrations.RunPython(drop_accept_suggestion_subs),
    ]
