# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 15:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pootle_translationproject', '0006_relink_or_drop_orphan_translationprojects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTPScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('score', models.FloatField(db_index=True)),
                ('reviewed', models.IntegerField(db_index=True, default=0)),
                ('suggested', models.IntegerField(db_index=True, default=0)),
                ('translated', models.IntegerField(db_index=True, default=0)),
                ('tp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scores', to='pootle_translationproject.TranslationProject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'db_table': 'pootle_user_tp_score',
            },
        ),
        migrations.AlterUniqueTogether(
            name='usertpscore',
            unique_together=set([('date', 'tp', 'user')]),
        ),
    ]
