# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 19:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_store', '0045_remove_suggestion_tmp_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pootle_score', '0002_set_user_scores'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStoreScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('score', models.FloatField(db_index=True)),
                ('reviewed', models.IntegerField(db_index=True, default=0)),
                ('suggested', models.IntegerField(db_index=True, default=0)),
                ('translated', models.IntegerField(db_index=True, default=0)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scores', to='pootle_store.Store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'db_table': 'pootle_user_store_score',
            },
        ),
        migrations.AlterUniqueTogether(
            name='userstorescore',
            unique_together=set([('date', 'store', 'user')]),
        ),
    ]
