# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_score', '0003_add_pootle_user_store_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstorescore',
            name='score',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='usertpscore',
            name='score',
            field=models.FloatField(db_index=True, default=0),
        ),
    ]
