# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-02 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_score', '0004_zero_default_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstorescore',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usertpscore',
            name='date',
            field=models.DateField(),
        ),
    ]
