#!/bin/sh

SRC_DIR=$(readlink -f `dirname $0`/..)

# Placeholders
YEAR_COPYRIGHT_PLACEHOLDER="YEAR THE PACKAGE'S COPYRIGHT HOLDER"
PACKAGE_VERSION_PLACEHOLDER="PACKAGE VERSION"
MSGID_BUGS_TO_PLACEHOLDER="Report-Msgid-Bugs-To:"

# Filename constants
POT_DIR="$SRC_DIR/locale/templates"
DJANGO_POT="$POT_DIR/LC_MESSAGES/django.po"
DJANGO_JS_POT="$POT_DIR/LC_MESSAGES/djangojs.po"
POOTLE_POT="$POT_DIR/pootle.pot"
POOTLE_JS_POT="$POT_DIR/pootle_js.pot"

# Header settings
YEAR=`date +%Y`
COPYRIGHT_HOLDER="Zuza Software Foundation (Translate.org.za)"
PACKAGE="Pootle"
VERSION=`egrep "^ver" $SRC_DIR/__version__.py | sed "s,.*(\(.*\)),\1,g" | sed "s,[ ],,g" | sed "s/,/./g"`
MSGID_BUGS_TO="translate-pootle@lists.sourceforge.net"

pushd . 2>&1 > /dev/null
cd $SRC_DIR

django-admin.py makemessages -e py,txt,html,conf -l templates
django-admin.py makemessages --ignore assets -d djangojs -l templates

# Header replacements
sed -i "" "s/$YEAR_COPYRIGHT_PLACEHOLDER/$YEAR $COPYRIGHT_HOLDER/" $DJANGO_POT
sed -i "" "s/$PACKAGE_VERSION_PLACEHOLDER/$PACKAGE $VERSION/" $DJANGO_POT
sed -i "" "s/$MSGID_BUGS_TO_PLACEHOLDER /$MSGID_BUGS_TO_PLACEHOLDER $MSGID_BUGS_TO/" $DJANGO_POT

sed -i "" "s/$YEAR_COPYRIGHT_PLACEHOLDER/$YEAR $COPYRIGHT_HOLDER/" $DJANGO_JS_POT
sed -i "" "s/$PACKAGE_VERSION_PLACEHOLDER/$PACKAGE $VERSION/" $DJANGO_JS_POT
sed -i "" "s/$MSGID_BUGS_TO_PLACEHOLDER /$MSGID_BUGS_TO_PLACEHOLDER $MSGID_BUGS_TO/" $DJANGO_JS_POT

mv $DJANGO_POT $POOTLE_POT
mv $DJANGO_JS_POT $POOTLE_JS_POT

popd  2>&1  >  /dev/null
