#!/bin/bash

set -e

INSTALL_DIR=$(readlink -f --canonicalize $(eval echo $INSTALL_DIR))

mkdir -p $INSTALL_DIR

cd $INSTALL_DIR

function get_requirement () {
    curl -sO https://raw.githubusercontent.com/translate/pootle/master/requirements/$1.txt
}

mkdir requirements
cd requirements
declare -a requirements=("_es_5" "base" "dev" "tests" "_docs" "_lint")
for i in "${requirements[@]}"
do
    get_requirement "$i"
done
cd ..

virtualenv .
. bin/activate \
  && pip install --no-cache-dir -qr requirements/dev.txt \
  && pip install --no-cache-dir -qr requirements/_es_5.txt \
  && pip install --no-cache-dir -q \
         codecov==2.0.15 \
         coverage==4.5.1 \
         coveralls==1.3.0 \
  && pyclean .

cd $INSTALL_DIR
curl -s -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
. ~/.nvm/nvm.sh

nvm install node
