# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-05 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_translationproject', '0003_realpath_can_be_none'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='translationproject',
            unique_together=set([('project', 'language'), ('language', 'project')]),
        ),
    ]
