# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_translationproject', '0006_relink_or_drop_orphan_translationprojects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translationproject',
            options={'base_manager_name': 'objects'},
        ),
    ]
