# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-02 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_translationproject', '0007_set_tp_base_manager_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationproject',
            name='language',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='pootle_language.Language'),
        ),
    ]
