# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-28 07:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_translationproject', '0008_remove_extra_indeces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translationproject',
            name='real_path',
        ),
    ]
