# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 14:42
from __future__ import unicode_literals

from django.db import migrations

def update_system_username(apps, schema_editor):
    users = apps.get_model("accounts.User").objects
    sysuser = users.filter(username="system").first()
    if sysuser:
        sysuser.full_name = "Pootle"
        sysuser.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_unicode_usernames_are_valid'),
    ]

    operations = [
        migrations.RunPython(update_system_username),
    ]
