# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_system_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hourly_rate',
        ),
    ]
