# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_set_username_unique_error_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='review_rate',
        ),
    ]
