# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/k-da/Documents/poxole/trunk/pootling/ui/MainEditor.ui'
#
# Created: Tue Sep 11 12:05:22 2007
#      by: PyQt4 UI code generator 4-snapshot-20070212
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(QtCore.QSize(QtCore.QRect(0,0,594,487).size()).expandedTo(MainWindow.minimumSizeHint()))

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(7))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(400,300))
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setWindowIcon(QtGui.QIcon("../images/pootling.png"))

        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0,0,594,29))
        self.menubar.setObjectName("menubar")

        self.menuBookmark = QtGui.QMenu(self.menubar)
        self.menuBookmark.setObjectName("menuBookmark")

        self.menuGo = QtGui.QMenu(self.menubar)
        self.menuGo.setObjectName("menuGo")

        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")

        self.menuOpen_Recent = QtGui.QMenu(self.menuFile)
        self.menuOpen_Recent.setIcon(QtGui.QIcon("../images/open.png"))
        self.menuOpen_Recent.setObjectName("menuOpen_Recent")

        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setEnabled(True)
        self.menuView.setObjectName("menuView")

        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")

        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")

        self.menuWindow = QtGui.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")

        self.menuToolbars = QtGui.QMenu(self.menuWindow)
        self.menuToolbars.setObjectName("menuToolbars")

        self.menu_Tool = QtGui.QMenu(self.menubar)
        self.menu_Tool.setObjectName("menu_Tool")

        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")

        self.menuProject = QtGui.QMenu(self.menubar)
        self.menuProject.setObjectName("menuProject")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.toolFile = QtGui.QToolBar(MainWindow)
        self.toolFile.setOrientation(QtCore.Qt.Horizontal)
        self.toolFile.setObjectName("toolFile")
        MainWindow.addToolBar(self.toolFile)

        self.toolEdit = QtGui.QToolBar(MainWindow)
        self.toolEdit.setEnabled(True)
        self.toolEdit.setOrientation(QtCore.Qt.Horizontal)
        self.toolEdit.setObjectName("toolEdit")
        MainWindow.addToolBar(self.toolEdit)

        self.toolNavigation = QtGui.QToolBar(MainWindow)
        self.toolNavigation.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.toolNavigation.setAcceptDrops(False)
        self.toolNavigation.setOrientation(QtCore.Qt.Horizontal)
        self.toolNavigation.setObjectName("toolNavigation")
        MainWindow.addToolBar(self.toolNavigation)

        self.toolFilter = QtGui.QToolBar(MainWindow)
        self.toolFilter.setOrientation(QtCore.Qt.Horizontal)
        self.toolFilter.setObjectName("toolFilter")
        MainWindow.addToolBar(self.toolFilter)

        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setIcon(QtGui.QIcon("../images/open.png"))
        self.actionOpen.setObjectName("actionOpen")

        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setEnabled(False)
        self.actionSave.setIcon(QtGui.QIcon("../images/save.png"))
        self.actionSave.setObjectName("actionSave")

        self.actionSaveas = QtGui.QAction(MainWindow)
        self.actionSaveas.setEnabled(False)
        self.actionSaveas.setIcon(QtGui.QIcon("../images/filesaveas.png"))
        self.actionSaveas.setObjectName("actionSaveas")

        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setIcon(QtGui.QIcon("../images/exit.png"))
        self.actionExit.setObjectName("actionExit")

        self.actionUndo = QtGui.QAction(MainWindow)
        self.actionUndo.setEnabled(False)
        self.actionUndo.setIcon(QtGui.QIcon("../images/undo.png"))
        self.actionUndo.setObjectName("actionUndo")

        self.actionRedo = QtGui.QAction(MainWindow)
        self.actionRedo.setEnabled(False)
        self.actionRedo.setIcon(QtGui.QIcon("../images/redo.png"))
        self.actionRedo.setObjectName("actionRedo")

        self.actionCut = QtGui.QAction(MainWindow)
        self.actionCut.setEnabled(False)
        self.actionCut.setIcon(QtGui.QIcon("../images/cut.png"))
        self.actionCut.setObjectName("actionCut")

        self.actionCopy = QtGui.QAction(MainWindow)
        self.actionCopy.setCheckable(False)
        self.actionCopy.setEnabled(False)
        self.actionCopy.setIcon(QtGui.QIcon("../images/copy.png"))
        self.actionCopy.setObjectName("actionCopy")

        self.actionPaste = QtGui.QAction(MainWindow)
        self.actionPaste.setEnabled(False)
        self.actionPaste.setIcon(QtGui.QIcon("../images/paste.png"))
        self.actionPaste.setObjectName("actionPaste")

        self.actionFind = QtGui.QAction(MainWindow)
        self.actionFind.setEnabled(False)
        self.actionFind.setIcon(QtGui.QIcon("../images/find.png"))
        self.actionFind.setObjectName("actionFind")

        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")

        self.actionShowMenuBar = QtGui.QAction(MainWindow)
        self.actionShowMenuBar.setObjectName("actionShowMenuBar")

        self.actionShowTUview = QtGui.QAction(MainWindow)
        self.actionShowTUview.setObjectName("actionShowTUview")

        self.actionAboutQT = QtGui.QAction(MainWindow)
        self.actionAboutQT.setObjectName("actionAboutQT")

        self.actionShow_MenuBar = QtGui.QAction(MainWindow)
        self.actionShow_MenuBar.setObjectName("actionShow_MenuBar")

        self.actionShow_TUview = QtGui.QAction(MainWindow)
        self.actionShow_TUview.setObjectName("actionShow_TUview")

        self.actionFirst = QtGui.QAction(MainWindow)
        self.actionFirst.setEnabled(False)
        self.actionFirst.setIcon(QtGui.QIcon("../images/first.png"))
        self.actionFirst.setObjectName("actionFirst")

        self.actionPrevious = QtGui.QAction(MainWindow)
        self.actionPrevious.setEnabled(False)
        self.actionPrevious.setIcon(QtGui.QIcon("../images/back.png"))
        self.actionPrevious.setObjectName("actionPrevious")

        self.actionNext = QtGui.QAction(MainWindow)
        self.actionNext.setEnabled(False)
        self.actionNext.setIcon(QtGui.QIcon("../images/forward.png"))
        self.actionNext.setObjectName("actionNext")

        self.actionLast = QtGui.QAction(MainWindow)
        self.actionLast.setEnabled(False)
        self.actionLast.setIcon(QtGui.QIcon("../images/last.png"))
        self.actionLast.setObjectName("actionLast")

        self.actionCopySource2Target = QtGui.QAction(MainWindow)
        self.actionCopySource2Target.setEnabled(False)
        self.actionCopySource2Target.setObjectName("actionCopySource2Target")

        self.actionToggleFuzzy = QtGui.QAction(MainWindow)
        self.actionToggleFuzzy.setEnabled(False)
        self.actionToggleFuzzy.setObjectName("actionToggleFuzzy")

        self.actionFile = QtGui.QAction(MainWindow)
        self.actionFile.setObjectName("actionFile")

        self.actionFind_Previous = QtGui.QAction(MainWindow)
        self.actionFind_Previous.setEnabled(False)
        self.actionFind_Previous.setObjectName("actionFind_Previous")

        self.actionFind_Next = QtGui.QAction(MainWindow)
        self.actionFind_Next.setEnabled(False)
        self.actionFind_Next.setObjectName("actionFind_Next")

        self.actionReplace = QtGui.QAction(MainWindow)
        self.actionReplace.setEnabled(False)
        self.actionReplace.setIcon(QtGui.QIcon("../images/replace.png"))
        self.actionReplace.setObjectName("actionReplace")

        self.actionFindNext = QtGui.QAction(MainWindow)
        self.actionFindNext.setEnabled(False)
        self.actionFindNext.setIcon(QtGui.QIcon("../images/next.png"))
        self.actionFindNext.setObjectName("actionFindNext")

        self.actionFindPrevious = QtGui.QAction(MainWindow)
        self.actionFindPrevious.setEnabled(False)
        self.actionFindPrevious.setIcon(QtGui.QIcon("../images/previous.png"))
        self.actionFindPrevious.setObjectName("actionFindPrevious")

        self.actionSelectAll = QtGui.QAction(MainWindow)
        self.actionSelectAll.setEnabled(False)
        self.actionSelectAll.setObjectName("actionSelectAll")

        self.actionEdit_Header = QtGui.QAction(MainWindow)
        self.actionEdit_Header.setEnabled(False)
        self.actionEdit_Header.setObjectName("actionEdit_Header")

        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setIcon(QtGui.QIcon("../images/configure.png"))
        self.actionPreferences.setObjectName("actionPreferences")

        self.actionToolbars = QtGui.QAction(MainWindow)
        self.actionToolbars.setObjectName("actionToolbars")

        self.actionFilterFuzzy = QtGui.QAction(MainWindow)
        self.actionFilterFuzzy.setCheckable(True)
        self.actionFilterFuzzy.setChecked(True)
        self.actionFilterFuzzy.setEnabled(False)
        self.actionFilterFuzzy.setIcon(QtGui.QIcon("../images/fuzzy.png"))
        self.actionFilterFuzzy.setObjectName("actionFilterFuzzy")

        self.actionFilterTranslated = QtGui.QAction(MainWindow)
        self.actionFilterTranslated.setCheckable(True)
        self.actionFilterTranslated.setChecked(True)
        self.actionFilterTranslated.setEnabled(False)
        self.actionFilterTranslated.setIcon(QtGui.QIcon("../images/translated.png"))
        self.actionFilterTranslated.setObjectName("actionFilterTranslated")

        self.actionFilterUntranslated = QtGui.QAction(MainWindow)
        self.actionFilterUntranslated.setCheckable(True)
        self.actionFilterUntranslated.setChecked(True)
        self.actionFilterUntranslated.setEnabled(False)
        self.actionFilterUntranslated.setIcon(QtGui.QIcon("../images/untranslated.png"))
        self.actionFilterUntranslated.setObjectName("actionFilterUntranslated")

        self.action_Close = QtGui.QAction(MainWindow)
        self.action_Close.setEnabled(False)
        self.action_Close.setIcon(QtGui.QIcon("../images/fileclose.png"))
        self.action_Close.setObjectName("action_Close")

        self.actionGoTo = QtGui.QAction(MainWindow)
        self.actionGoTo.setEnabled(False)
        self.actionGoTo.setObjectName("actionGoTo")

        self.actionAddBookmarks = QtGui.QAction(MainWindow)
        self.actionAddBookmarks.setEnabled(False)
        self.actionAddBookmarks.setIcon(QtGui.QIcon("../images/bookmarkadd.png"))
        self.actionAddBookmarks.setObjectName("actionAddBookmarks")

        self.actionClearBookmarks = QtGui.QAction(MainWindow)
        self.actionClearBookmarks.setObjectName("actionClearBookmarks")

        self.actionAuto_translate = QtGui.QAction(MainWindow)
        self.actionAuto_translate.setObjectName("actionAuto_translate")

        self.actionCatalogManager = QtGui.QAction(MainWindow)
        self.actionCatalogManager.setIcon(QtGui.QIcon("../images/catalog.png"))
        self.actionCatalogManager.setObjectName("actionCatalogManager")

        self.actionBuildGlossary = QtGui.QAction(MainWindow)
        self.actionBuildGlossary.setEnabled(True)
        self.actionBuildGlossary.setObjectName("actionBuildGlossary")

        self.actionCopySearchResult2Target = QtGui.QAction(MainWindow)
        self.actionCopySearchResult2Target.setEnabled(False)
        self.actionCopySearchResult2Target.setIcon(QtGui.QIcon("../images/source.png"))
        self.actionCopySearchResult2Target.setObjectName("actionCopySearchResult2Target")

        self.actionBuild_TM = QtGui.QAction(MainWindow)
        self.actionBuild_TM.setIcon(QtGui.QIcon("../images/memory.png"))
        self.actionBuild_TM.setObjectName("actionBuild_TM")

        self.actionGlossary = QtGui.QAction(MainWindow)
        self.actionGlossary.setObjectName("actionGlossary")

        self.actionAuto_translate1 = QtGui.QAction(MainWindow)
        self.actionAuto_translate1.setObjectName("actionAuto_translate1")

        self.actionNewPro = QtGui.QAction(MainWindow)
        self.actionNewPro.setIcon(QtGui.QIcon("../images/projectNew.png"))
        self.actionNewPro.setObjectName("actionNewPro")

        self.actionOpenPro = QtGui.QAction(MainWindow)
        self.actionOpenPro.setIcon(QtGui.QIcon("../images/projectOpen.png"))
        self.actionOpenPro.setObjectName("actionOpenPro")

        self.actionClear_Fuzzies = QtGui.QAction(MainWindow)
        self.actionClear_Fuzzies.setEnabled(False)
        self.actionClear_Fuzzies.setObjectName("actionClear_Fuzzies")

        self.actionProperties = QtGui.QAction(MainWindow)
        self.actionProperties.setEnabled(False)
        self.actionProperties.setIcon(QtGui.QIcon("../images/properties.png"))
        self.actionProperties.setObjectName("actionProperties")
        self.menuBookmark.addAction(self.actionAddBookmarks)
        self.menuBookmark.addAction(self.actionClearBookmarks)
        self.menuBookmark.addSeparator()
        self.menuGo.addAction(self.actionFirst)
        self.menuGo.addAction(self.actionPrevious)
        self.menuGo.addAction(self.actionNext)
        self.menuGo.addAction(self.actionLast)
        self.menuGo.addSeparator()
        self.menuGo.addAction(self.actionGoTo)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.menuOpen_Recent.menuAction())
        self.menuFile.addAction(self.action_Close)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveas)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuView.addAction(self.actionFilterUntranslated)
        self.menuView.addAction(self.actionFilterFuzzy)
        self.menuView.addAction(self.actionFilterTranslated)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionFind)
        self.menuEdit.addAction(self.actionFindPrevious)
        self.menuEdit.addAction(self.actionFindNext)
        self.menuEdit.addAction(self.actionReplace)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCopySource2Target)
        self.menuEdit.addAction(self.actionCopySearchResult2Target)
        self.menuEdit.addAction(self.actionToggleFuzzy)
        self.menuEdit.addAction(self.actionClear_Fuzzies)
        self.menuEdit.addAction(self.actionEdit_Header)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionAboutQT)
        self.menuWindow.addSeparator()
        self.menuWindow.addSeparator()
        self.menuWindow.addAction(self.menuToolbars.menuAction())
        self.menu_Tool.addSeparator()
        self.menu_Tool.addAction(self.actionCatalogManager)
        self.menu_Tool.addAction(self.actionAuto_translate)
        self.menuSettings.addAction(self.actionPreferences)
        self.menuSettings.addAction(self.actionBuild_TM)
        self.menuSettings.addAction(self.actionGlossary)
        self.menuProject.addAction(self.actionNewPro)
        self.menuProject.addAction(self.actionOpenPro)
        self.menuProject.addAction(self.actionProperties)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuGo.menuAction())
        self.menubar.addAction(self.menuBookmark.menuAction())
        self.menubar.addAction(self.menuProject.menuAction())
        self.menubar.addAction(self.menu_Tool.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolFile.addAction(self.actionSave)
        self.toolFile.addAction(self.actionSaveas)
        self.toolEdit.addAction(self.actionUndo)
        self.toolEdit.addAction(self.actionRedo)
        self.toolEdit.addAction(self.actionCut)
        self.toolEdit.addAction(self.actionCopy)
        self.toolEdit.addAction(self.actionPaste)
        self.toolNavigation.addAction(self.actionFirst)
        self.toolNavigation.addAction(self.actionPrevious)
        self.toolNavigation.addAction(self.actionNext)
        self.toolNavigation.addAction(self.actionLast)
        self.toolFilter.addAction(self.actionFilterUntranslated)
        self.toolFilter.addAction(self.actionFilterFuzzy)
        self.toolFilter.addAction(self.actionFilterTranslated)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.menuBookmark.setTitle(QtGui.QApplication.translate("MainWindow", "&Bookmarks", None, QtGui.QApplication.UnicodeUTF8))
        self.menuGo.setTitle(QtGui.QApplication.translate("MainWindow", "&Go", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOpen_Recent.setStatusTip(QtGui.QApplication.translate("MainWindow", "Open the file that used to be opened.", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOpen_Recent.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<h3>Open Recent</h>Use this to open the file that used to be opened.", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOpen_Recent.setTitle(QtGui.QApplication.translate("MainWindow", "Open &Recent", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "&View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "&Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuWindow.setTitle(QtGui.QApplication.translate("MainWindow", "&Window", None, QtGui.QApplication.UnicodeUTF8))
        self.menuToolbars.setStatusTip(QtGui.QApplication.translate("MainWindow", "Hide/Show the toolbars", None, QtGui.QApplication.UnicodeUTF8))
        self.menuToolbars.setTitle(QtGui.QApplication.translate("MainWindow", "&Toolbars", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Tool.setTitle(QtGui.QApplication.translate("MainWindow", "&Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSettings.setTitle(QtGui.QApplication.translate("MainWindow", "&Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.menuProject.setTitle(QtGui.QApplication.translate("MainWindow", "&Project", None, QtGui.QApplication.UnicodeUTF8))
        self.toolFile.setWindowTitle(QtGui.QApplication.translate("MainWindow", "&File Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.toolFile.setToolTip(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.toolFile.setStatusTip(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.toolFile.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<h3>Save File</h3>Save the contents of current editor.", None, QtGui.QApplication.UnicodeUTF8))
        self.toolEdit.setWindowTitle(QtGui.QApplication.translate("MainWindow", "&Edit Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.toolNavigation.setWindowTitle(QtGui.QApplication.translate("MainWindow", "&Navigation Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.toolFilter.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Fil&ter Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "&Open...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setIconText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setToolTip(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setStatusTip(QtGui.QApplication.translate("MainWindow", "Open a file...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<h3>Open</h3>Use this to open existed file for edit.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setStatusTip(QtGui.QApplication.translate("MainWindow", "Save the current file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<h3>Save</h3>Use this to save the current file.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveas.setText(QtGui.QApplication.translate("MainWindow", "Save &As...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveas.setIconText(QtGui.QApplication.translate("MainWindow", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveas.setToolTip(QtGui.QApplication.translate("MainWindow", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveas.setStatusTip(QtGui.QApplication.translate("MainWindow", "Save the current contents to a new file...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveas.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<h3>Save As</h3>Use this to save the current contents to a new file. The file name can be entered in a file selection dialog.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveas.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setToolTip(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setStatusTip(QtGui.QApplication.translate("MainWindow", "Quit the application", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<h3>Quit</h3>Use this to quit the application. Any unsaved changes will be prompted.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo.setText(QtGui.QApplication.translate("MainWindow", "&Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo.setStatusTip(QtGui.QApplication.translate("MainWindow", "Undo the last change", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<h3>Undo</h3>Use this to undo the last change done in the editor.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Z", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRedo.setText(QtGui.QApplication.translate("MainWindow", "Re&do", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRedo.setStatusTip(QtGui.QApplication.translate("MainWindow", "Redo the last change", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRedo.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<h3>Redo</h3>Use this to redo the last change done in the editor.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRedo.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+Z", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setText(QtGui.QApplication.translate("MainWindow", "Cu&t", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setStatusTip(QtGui.QApplication.translate("MainWindow", "Cut the selected text", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<h3>Cut</h3>Use this to cut the selected text to the clipboard.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+X", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setText(QtGui.QApplication.translate("MainWindow", "&Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setStatusTip(QtGui.QApplication.translate("MainWindow", "Copy the selected text", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<h3>Copy</h3>Use this to copy the selected text to the clipboard.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setText(QtGui.QApplication.translate("MainWindow", "&Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setIconText(QtGui.QApplication.translate("MainWindow", "Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setToolTip(QtGui.QApplication.translate("MainWindow", "Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setStatusTip(QtGui.QApplication.translate("MainWindow", "Paste the last cut/copied text", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<h3>Paste</h3>Use this to paste the last cut/copies text from the clipboard to the editor.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+V", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFind.setText(QtGui.QApplication.translate("MainWindow", "&Find", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFind.setStatusTip(QtGui.QApplication.translate("MainWindow", "Find text in the shown strings...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFind.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<h3>Find</h3>Use this to find text in the shown strings. The find dialog will show at the bottom of the editor.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFind.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+F", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "&About Pootling", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setStatusTip(QtGui.QApplication.translate("MainWindow", "Display some information about this software...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<h3>About Pootling</h3>Display some information about this software.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowMenuBar.setText(QtGui.QApplication.translate("MainWindow", "Show MenuBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowMenuBar.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+M", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowTUview.setText(QtGui.QApplication.translate("MainWindow", "Show TUview", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowTUview.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+T", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAboutQT.setText(QtGui.QApplication.translate("MainWindow", "About &Qt", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAboutQT.setIconText(QtGui.QApplication.translate("MainWindow", "About Qt", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAboutQT.setStatusTip(QtGui.QApplication.translate("MainWindow", "Display some information about the Qt Toolkit...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAboutQT.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<h3>About Qt</h3>Display some information about the Qt Toolkit.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_MenuBar.setText(QtGui.QApplication.translate("MainWindow", "Show MenuBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_TUview.setText(QtGui.QApplication.translate("MainWindow", "Show TUview", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFirst.setText(QtGui.QApplication.translate("MainWindow", "&First", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFirst.setToolTip(QtGui.QApplication.translate("MainWindow", "First", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFirst.setStatusTip(QtGui.QApplication.translate("MainWindow", "Go to the first string", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFirst.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<h3>First</h3>Go to the first string in the table.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFirst.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+PgUp", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrevious.setText(QtGui.QApplication.translate("MainWindow", "&Previous", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrevious.setStatusTip(QtGui.QApplication.translate("MainWindow", "Go to the previous string", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrevious.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<h3>Previous</h3>Go to the previous string in the table.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrevious.setShortcut(QtGui.QApplication.translate("MainWindow", "PgUp", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext.setText(QtGui.QApplication.translate("MainWindow", "&Next", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext.setStatusTip(QtGui.QApplication.translate("MainWindow", "Go to the next string", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<h3>Next</h3>Go to the next string in the table.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext.setShortcut(QtGui.QApplication.translate("MainWindow", "PgDown", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLast.setText(QtGui.QApplication.translate("MainWindow", "&Last", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLast.setStatusTip(QtGui.QApplication.translate("MainWindow", "Go to the last string", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLast.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<h3>Last</h3>Go to the last string in the table.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLast.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+PgDown", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopySource2Target.setText(QtGui.QApplication.translate("MainWindow", "Cop&y Source To Target", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopySource2Target.setIconText(QtGui.QApplication.translate("MainWindow", "Copy Source To Target", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopySource2Target.setToolTip(QtGui.QApplication.translate("MainWindow", "Copy Source To Target", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopySource2Target.setStatusTip(QtGui.QApplication.translate("MainWindow", "Copy current string from source field to target field", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopySource2Target.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<h3>Copy Source To Target</h3>Use this to copy current string from source field to target field.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopySource2Target.setShortcut(QtGui.QApplication.translate("MainWindow", "F2", None, QtGui.QApplication.UnicodeUTF8))
        self.actionToggleFuzzy.setText(QtGui.QApplication.translate("MainWindow", "To&ggle Fuzzy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionToggleFuzzy.setIconText(QtGui.QApplication.translate("MainWindow", "Toggle Fuzzy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionToggleFuzzy.setToolTip(QtGui.QApplication.translate("MainWindow", "Toggle Fuzzy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionToggleFuzzy.setStatusTip(QtGui.QApplication.translate("MainWindow", "Toggle fuzzy for current string", None, QtGui.QApplication.UnicodeUTF8))
        self.actionToggleFuzzy.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<h3>Toggle Fuzzy</h3>Use this to set current string to fuzzy or unset it.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionToggleFuzzy.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+U", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFile.setText(QtGui.QApplication.translate("MainWindow", "file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFind_Previous.setText(QtGui.QApplication.translate("MainWindow", "Find Previous", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFind_Next.setText(QtGui.QApplication.translate("MainWindow", "Find Next", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReplace.setText(QtGui.QApplication.translate("MainWindow", "&Replace", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReplace.setStatusTip(QtGui.QApplication.translate("MainWindow", "Replace text in the shown strings...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReplace.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<h3>Replace</h3>Use this to find text in the shown strings to replace. The find and replace dialog will show at the bottom of the editor.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReplace.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFindNext.setText(QtGui.QApplication.translate("MainWindow", "Find &Next", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFindNext.setIconText(QtGui.QApplication.translate("MainWindow", "Find Next", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFindNext.setToolTip(QtGui.QApplication.translate("MainWindow", "Find Next", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFindNext.setStatusTip(QtGui.QApplication.translate("MainWindow", "Find next occurrance of text.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFindNext.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<h3>Find Next</h3>Use this to find the next occurrance of search text in the shown strings.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFindNext.setShortcut(QtGui.QApplication.translate("MainWindow", "F3", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFindPrevious.setText(QtGui.QApplication.translate("MainWindow", "Find Pre&vious", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFindPrevious.setStatusTip(QtGui.QApplication.translate("MainWindow", "Find previous occurrance of text.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFindPrevious.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<h3>Find Previous</h3>Use this to find the previous occurrance of search text in the shown strings.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFindPrevious.setShortcut(QtGui.QApplication.translate("MainWindow", "Shift+F3", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelectAll.setText(QtGui.QApplication.translate("MainWindow", "Select &All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelectAll.setStatusTip(QtGui.QApplication.translate("MainWindow", "Select all text", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelectAll.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<h3>Select all text</h3>Select all text in the current window.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelectAll.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEdit_Header.setText(QtGui.QApplication.translate("MainWindow", "&Header...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEdit_Header.setStatusTip(QtGui.QApplication.translate("MainWindow", "Open header dialog...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEdit_Header.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<h3>Open header dialog</h3>Use this to open the dialog to edit the header information.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEdit_Header.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+H", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setText(QtGui.QApplication.translate("MainWindow", "&Preferences...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setToolTip(QtGui.QApplication.translate("MainWindow", "Preferences...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setStatusTip(QtGui.QApplication.translate("MainWindow", "Set common options for personality, font and color, translation memory and glossary, and save.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<h3>Preferences</h3>Use this to set common options for personality, font and color, translation memory and glossary, and save.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionToolbars.setText(QtGui.QApplication.translate("MainWindow", "Toolbars", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFilterFuzzy.setText(QtGui.QApplication.translate("MainWindow", "&Fuzzy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFilterFuzzy.setToolTip(QtGui.QApplication.translate("MainWindow", "Show/Hide fuzzy strings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFilterFuzzy.setStatusTip(QtGui.QApplication.translate("MainWindow", "Show or hide the fuzzy strings.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFilterFuzzy.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<h3>Fuzzy</h3>Use this to show or hide the fuzzy strings.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFilterFuzzy.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Alt+F", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFilterTranslated.setText(QtGui.QApplication.translate("MainWindow", "&Translated", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFilterTranslated.setToolTip(QtGui.QApplication.translate("MainWindow", "Show/Hide translated strings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFilterTranslated.setStatusTip(QtGui.QApplication.translate("MainWindow", "Show or hide the translated strings.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFilterTranslated.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<h3>Translated</h3>Use this show or hide the translated strings.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFilterTranslated.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Alt+T", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFilterUntranslated.setText(QtGui.QApplication.translate("MainWindow", "&Untranslated", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFilterUntranslated.setToolTip(QtGui.QApplication.translate("MainWindow", "Show/Hide untranslated strings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFilterUntranslated.setStatusTip(QtGui.QApplication.translate("MainWindow", "Show or hide the untranslated strings.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFilterUntranslated.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<h3>Untranslated</h3>Use this to show or hide the untranslated strings.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFilterUntranslated.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Alt+U", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Close.setText(QtGui.QApplication.translate("MainWindow", "&Close", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Close.setStatusTip(QtGui.QApplication.translate("MainWindow", "Close the current opened file", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Close.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<h3>Close the current file</h3>Use this to close the current opened file.", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Close.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+W", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGoTo.setText(QtGui.QApplication.translate("MainWindow", "&String Number...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGoTo.setIconText(QtGui.QApplication.translate("MainWindow", "String Number", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGoTo.setToolTip(QtGui.QApplication.translate("MainWindow", "String Number", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGoTo.setStatusTip(QtGui.QApplication.translate("MainWindow", "Go to string number...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGoTo.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<h3>GoTo String</h3>Go to the string number specified by user.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGoTo.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+G", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddBookmarks.setText(QtGui.QApplication.translate("MainWindow", "&Add Bookmarks", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddBookmarks.setStatusTip(QtGui.QApplication.translate("MainWindow", "Add a bookmark of the current string", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddBookmarks.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<h3>Add Bookmarks</h3>Use this to add a bookmark of the current string", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddBookmarks.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+B", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClearBookmarks.setText(QtGui.QApplication.translate("MainWindow", "&Clear Bookmarks", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClearBookmarks.setStatusTip(QtGui.QApplication.translate("MainWindow", "Clear all the bookmarks", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClearBookmarks.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<h3>Clear Bookmarks</h3>Use this to clear all the bookmarks.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAuto_translate.setText(QtGui.QApplication.translate("MainWindow", "&Auto Translate", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCatalogManager.setText(QtGui.QApplication.translate("MainWindow", "Catalog Manager...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCatalogManager.setStatusTip(QtGui.QApplication.translate("MainWindow", "Open Catalog Manager window...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCatalogManager.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<h3>Catalog Manager</h3>Use this to open Catalog Manager window.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBuildGlossary.setText(QtGui.QApplication.translate("MainWindow", "Gl&ossary", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopySearchResult2Target.setText(QtGui.QApplication.translate("MainWindow", "Copy &Translation To Target", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopySearchResult2Target.setIconText(QtGui.QApplication.translate("MainWindow", "Copy Translation To Target", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopySearchResult2Target.setToolTip(QtGui.QApplication.translate("MainWindow", "Copy Translation To Target", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopySearchResult2Target.setStatusTip(QtGui.QApplication.translate("MainWindow", "Copy the most similar translation to target field.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopySearchResult2Target.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<h3>Copy Translation To Target</h3>Use this to copy the most similar translation to target field.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBuild_TM.setText(QtGui.QApplication.translate("MainWindow", "Build TM...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBuild_TM.setToolTip(QtGui.QApplication.translate("MainWindow", "Build the translation memory.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBuild_TM.setStatusTip(QtGui.QApplication.translate("MainWindow", "Build the translation memory.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBuild_TM.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<h3>Build TM</h3>Use this to build the translation memory.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGlossary.setText(QtGui.QApplication.translate("MainWindow", "Build Gl&ossary...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGlossary.setIconText(QtGui.QApplication.translate("MainWindow", "Build Glossary", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGlossary.setToolTip(QtGui.QApplication.translate("MainWindow", "Build the glossary", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGlossary.setStatusTip(QtGui.QApplication.translate("MainWindow", "Build the glossary", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGlossary.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<h3>Build Glossary</h3>Use this to build the glossary.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAuto_translate1.setText(QtGui.QApplication.translate("MainWindow", "Auto Translate", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAuto_translate1.setStatusTip(QtGui.QApplication.translate("MainWindow", "Translate the whole strings automatically.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAuto_translate1.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<h3></h3>Use this to translate the whole strings automatically.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewPro.setText(QtGui.QApplication.translate("MainWindow", "&New...   ", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewPro.setStatusTip(QtGui.QApplication.translate("MainWindow", "This opens a dialog for entering  the information for a new project...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewPro.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<h3>New</h3>Use this to open a dialog for entering  the information for a new project.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenPro.setText(QtGui.QApplication.translate("MainWindow", "&Open...   ", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenPro.setStatusTip(QtGui.QApplication.translate("MainWindow", "This open an existing project...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenPro.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<h3>Open</h3>Use this to open an existing project.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear_Fuzzies.setText(QtGui.QApplication.translate("MainWindow", "Clear All Fuzzy Strings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear_Fuzzies.setIconText(QtGui.QApplication.translate("MainWindow", "Clear All Fuzzy Strings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear_Fuzzies.setToolTip(QtGui.QApplication.translate("MainWindow", "Clear All Fuzzy Strings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear_Fuzzies.setStatusTip(QtGui.QApplication.translate("MainWindow", "Clear all fuzzy status", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear_Fuzzies.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<h3>Clear All Fuzzy Strings</h3>This will take out the fuzzy status from all strings. You might lose some translation process  information, and this action cannot be undone. You should uncheck all options in Preferences/TM-Glossary for speed improvement. Are you sure you want to clear all fuzzies?", None, QtGui.QApplication.UnicodeUTF8))
        self.actionProperties.setText(QtGui.QApplication.translate("MainWindow", "&Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.actionProperties.setStatusTip(QtGui.QApplication.translate("MainWindow", "Open a Project Properties dialog...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionProperties.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<h3>Properties</h3>Use this to open a current project properties dialog. Here, you can change the project name, path, language, files\' location.", None, QtGui.QApplication.UnicodeUTF8))



if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
