# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'unknown'
#
# Created: Wed Sep 12 11:54:24 2007
#      by: PyQt4 UI code generator 4.0
#
# WARNING! All changes made in this file will be lost!

import sys
from PyQt4 import QtCore, QtGui

class Ui_frmPreference(object):
    def setupUi(self, frmPreference):
        frmPreference.setObjectName("frmPreference")
        frmPreference.resize(QtCore.QSize(QtCore.QRect(0,0,570,372).size()).expandedTo(frmPreference.minimumSizeHint()))

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(7))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(frmPreference.sizePolicy().hasHeightForWidth())
        frmPreference.setSizePolicy(sizePolicy)

        self.gridlayout = QtGui.QGridLayout(frmPreference)
        self.gridlayout.setMargin(9)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName("gridlayout")

        self.frame = QtGui.QFrame(frmPreference)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")

        self.gridlayout1 = QtGui.QGridLayout(self.frame)
        self.gridlayout1.setMargin(0)
        self.gridlayout1.setSpacing(6)
        self.gridlayout1.setObjectName("gridlayout1")

        self.stackedWidget = QtGui.QStackedWidget(self.frame)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(7))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0,0))
        self.stackedWidget.setFrameShape(QtGui.QFrame.StyledPanel)
        self.stackedWidget.setFrameShadow(QtGui.QFrame.Plain)
        self.stackedWidget.setLineWidth(1)
        self.stackedWidget.setObjectName("stackedWidget")

        self.personal = QtGui.QWidget()
        self.personal.setObjectName("personal")

        self.gridlayout2 = QtGui.QGridLayout(self.personal)
        self.gridlayout2.setMargin(9)
        self.gridlayout2.setSpacing(6)
        self.gridlayout2.setObjectName("gridlayout2")

        self.frame_2 = QtGui.QFrame(self.personal)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setLineWidth(1)
        self.frame_2.setObjectName("frame_2")

        self.gridlayout3 = QtGui.QGridLayout(self.frame_2)
        self.gridlayout3.setMargin(0)
        self.gridlayout3.setSpacing(6)
        self.gridlayout3.setObjectName("gridlayout3")

        self.spinBox = QtGui.QSpinBox(self.frame_2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox.sizePolicy().hasHeightForWidth())
        self.spinBox.setSizePolicy(sizePolicy)
        self.spinBox.setMaximum(10)
        self.spinBox.setMinimum(1)
        self.spinBox.setSingleStep(1)
        self.spinBox.setProperty("value",QtCore.QVariant(2))
        self.spinBox.setObjectName("spinBox")
        self.gridlayout3.addWidget(self.spinBox,4,2,1,2)

        self.lineEqaution = QtGui.QLineEdit(self.frame_2)
        self.lineEqaution.setObjectName("lineEqaution")
        self.gridlayout3.addWidget(self.lineEqaution,6,0,1,4)

        self.label_3 = QtGui.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.gridlayout3.addWidget(self.label_3,4,0,1,2)

        self.label_2 = QtGui.QLabel(self.frame_2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(5))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridlayout3.addWidget(self.label_2,5,0,1,2)

        self.label1 = QtGui.QLabel(self.frame_2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1.sizePolicy().hasHeightForWidth())
        self.label1.setSizePolicy(sizePolicy)
        self.label1.setTextFormat(QtCore.Qt.AutoText)
        self.label1.setObjectName("label1")
        self.gridlayout3.addWidget(self.label1,0,0,1,1)

        self.UserName = QtGui.QLineEdit(self.frame_2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UserName.sizePolicy().hasHeightForWidth())
        self.UserName.setSizePolicy(sizePolicy)
        self.UserName.setMaxLength(32768)
        self.UserName.setObjectName("UserName")
        self.gridlayout3.addWidget(self.UserName,0,1,1,3)

        self.EmailAddress = QtGui.QLineEdit(self.frame_2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EmailAddress.sizePolicy().hasHeightForWidth())
        self.EmailAddress.setSizePolicy(sizePolicy)
        self.EmailAddress.setObjectName("EmailAddress")
        self.gridlayout3.addWidget(self.EmailAddress,1,1,1,3)

        self.label2 = QtGui.QLabel(self.frame_2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label2.sizePolicy().hasHeightForWidth())
        self.label2.setSizePolicy(sizePolicy)
        self.label2.setObjectName("label2")
        self.gridlayout3.addWidget(self.label2,1,0,1,1)

        self.lineFullLang = QtGui.QLineEdit(self.frame_2)
        self.lineFullLang.setObjectName("lineFullLang")
        self.gridlayout3.addWidget(self.lineFullLang,2,3,1,1)

        self.cbxLanguageCode = QtGui.QComboBox(self.frame_2)
        self.cbxLanguageCode.setEnabled(True)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbxLanguageCode.sizePolicy().hasHeightForWidth())
        self.cbxLanguageCode.setSizePolicy(sizePolicy)
        self.cbxLanguageCode.setAcceptDrops(False)
        self.cbxLanguageCode.setEditable(True)
        self.cbxLanguageCode.setObjectName("cbxLanguageCode")
        self.gridlayout3.addWidget(self.cbxLanguageCode,2,1,1,1)

        self.label4 = QtGui.QLabel(self.frame_2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label4.sizePolicy().hasHeightForWidth())
        self.label4.setSizePolicy(sizePolicy)
        self.label4.setObjectName("label4")
        self.gridlayout3.addWidget(self.label4,2,0,1,1)

        self.label3 = QtGui.QLabel(self.frame_2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label3.sizePolicy().hasHeightForWidth())
        self.label3.setSizePolicy(sizePolicy)
        self.label3.setObjectName("label3")
        self.gridlayout3.addWidget(self.label3,2,2,1,1)

        self.SupportTeam = QtGui.QLineEdit(self.frame_2)
        self.SupportTeam.setObjectName("SupportTeam")
        self.gridlayout3.addWidget(self.SupportTeam,3,1,1,3)

        self.label5 = QtGui.QLabel(self.frame_2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label5.sizePolicy().hasHeightForWidth())
        self.label5.setSizePolicy(sizePolicy)
        self.label5.setObjectName("label5")
        self.gridlayout3.addWidget(self.label5,3,0,1,1)
        self.gridlayout2.addWidget(self.frame_2,2,0,1,1)

        self.label = QtGui.QLabel(self.personal)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(5))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)

        font = QtGui.QFont(self.label.font())
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridlayout2.addWidget(self.label,0,0,1,1)

        self.line = QtGui.QFrame(self.personal)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridlayout2.addWidget(self.line,1,0,1,1)

        spacerItem = QtGui.QSpacerItem(20,40,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.gridlayout2.addItem(spacerItem,3,0,1,1)
        self.stackedWidget.addWidget(self.personal)

        self.interface = QtGui.QWidget()
        self.interface.setObjectName("interface")

        self.gridlayout4 = QtGui.QGridLayout(self.interface)
        self.gridlayout4.setMargin(9)
        self.gridlayout4.setSpacing(6)
        self.gridlayout4.setObjectName("gridlayout4")

        self.line_2 = QtGui.QFrame(self.interface)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridlayout4.addWidget(self.line_2,1,0,1,1)

        self.label_4 = QtGui.QLabel(self.interface)

        font = QtGui.QFont(self.label_4.font())
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridlayout4.addWidget(self.label_4,0,0,1,1)

        self.frame2 = QtGui.QFrame(self.interface)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(7))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame2.sizePolicy().hasHeightForWidth())
        self.frame2.setSizePolicy(sizePolicy)
        self.frame2.setObjectName("frame2")

        self.gridlayout5 = QtGui.QGridLayout(self.frame2)
        self.gridlayout5.setMargin(9)
        self.gridlayout5.setSpacing(6)
        self.gridlayout5.setObjectName("gridlayout5")

        self.bntAdjustAllFont = QtGui.QPushButton(self.frame2)
        self.bntAdjustAllFont.setObjectName("bntAdjustAllFont")
        self.gridlayout5.addWidget(self.bntAdjustAllFont,7,1,1,1)

        self.bntDefaultsFont = QtGui.QPushButton(self.frame2)
        self.bntDefaultsFont.setObjectName("bntDefaultsFont")
        self.gridlayout5.addWidget(self.bntDefaultsFont,7,2,1,1)

        self.bntDefaultsColor = QtGui.QPushButton(self.frame2)
        self.bntDefaultsColor.setObjectName("bntDefaultsColor")
        self.gridlayout5.addWidget(self.bntDefaultsColor,7,3,1,1)

        self.btnColorGlossary = QtGui.QPushButton(self.frame2)
        self.btnColorGlossary.setObjectName("btnColorGlossary")
        self.gridlayout5.addWidget(self.btnColorGlossary,6,3,1,1)

        self.lblTarget = QtGui.QLabel(self.frame2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(1))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTarget.sizePolicy().hasHeightForWidth())
        self.lblTarget.setSizePolicy(sizePolicy)
        self.lblTarget.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblTarget.setObjectName("lblTarget")
        self.gridlayout5.addWidget(self.lblTarget,3,1,1,1)

        self.lblSource = QtGui.QLabel(self.frame2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(1))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSource.sizePolicy().hasHeightForWidth())
        self.lblSource.setSizePolicy(sizePolicy)
        self.lblSource.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblSource.setObjectName("lblSource")
        self.gridlayout5.addWidget(self.lblSource,2,1,1,1)

        self.lblOverView = QtGui.QLabel(self.frame2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(1))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOverView.sizePolicy().hasHeightForWidth())
        self.lblOverView.setSizePolicy(sizePolicy)
        self.lblOverView.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblOverView.setObjectName("lblOverView")
        self.gridlayout5.addWidget(self.lblOverView,1,1,1,1)

        self.bntFontOverviewHeader = QtGui.QPushButton(self.frame2)
        self.bntFontOverviewHeader.setObjectName("bntFontOverviewHeader")
        self.gridlayout5.addWidget(self.bntFontOverviewHeader,0,2,1,1)

        self.bntFontOverview = QtGui.QPushButton(self.frame2)
        self.bntFontOverview.setObjectName("bntFontOverview")
        self.gridlayout5.addWidget(self.bntFontOverview,1,2,1,1)

        self.bntFontSource = QtGui.QPushButton(self.frame2)
        self.bntFontSource.setObjectName("bntFontSource")
        self.gridlayout5.addWidget(self.bntFontSource,2,2,1,1)

        self.bntFontTarget = QtGui.QPushButton(self.frame2)
        self.bntFontTarget.setObjectName("bntFontTarget")
        self.gridlayout5.addWidget(self.bntFontTarget,3,2,1,1)

        self.btnColorOverview = QtGui.QPushButton(self.frame2)
        self.btnColorOverview.setObjectName("btnColorOverview")
        self.gridlayout5.addWidget(self.btnColorOverview,1,3,1,1)

        self.btnColorSource = QtGui.QPushButton(self.frame2)
        self.btnColorSource.setObjectName("btnColorSource")
        self.gridlayout5.addWidget(self.btnColorSource,2,3,1,1)

        self.btnColorTarget = QtGui.QPushButton(self.frame2)
        self.btnColorTarget.setObjectName("btnColorTarget")
        self.gridlayout5.addWidget(self.btnColorTarget,3,3,1,1)

        self.label4_3 = QtGui.QLabel(self.frame2)
        self.label4_3.setObjectName("label4_3")
        self.gridlayout5.addWidget(self.label4_3,3,0,1,1)

        self.label2_5 = QtGui.QLabel(self.frame2)
        self.label2_5.setScaledContents(True)
        self.label2_5.setWordWrap(True)
        self.label2_5.setIndent(0)
        self.label2_5.setObjectName("label2_5")
        self.gridlayout5.addWidget(self.label2_5,1,0,1,1)

        self.label2_4 = QtGui.QLabel(self.frame2)
        self.label2_4.setScaledContents(True)
        self.label2_4.setWordWrap(True)
        self.label2_4.setIndent(0)
        self.label2_4.setObjectName("label2_4")
        self.gridlayout5.addWidget(self.label2_4,0,0,1,1)

        self.Source_2 = QtGui.QLabel(self.frame2)
        self.Source_2.setObjectName("Source_2")
        self.gridlayout5.addWidget(self.Source_2,2,0,1,1)

        self.lblsupportteam_2 = QtGui.QLabel(self.frame2)
        self.lblsupportteam_2.setObjectName("lblsupportteam_2")
        self.gridlayout5.addWidget(self.lblsupportteam_2,4,0,1,1)

        self.lblComment = QtGui.QLabel(self.frame2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(1))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblComment.sizePolicy().hasHeightForWidth())
        self.lblComment.setSizePolicy(sizePolicy)
        self.lblComment.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblComment.setObjectName("lblComment")
        self.gridlayout5.addWidget(self.lblComment,4,1,1,1)

        self.bntFontComment = QtGui.QPushButton(self.frame2)
        self.bntFontComment.setObjectName("bntFontComment")
        self.gridlayout5.addWidget(self.bntFontComment,4,2,1,1)

        self.btnColorComment = QtGui.QPushButton(self.frame2)
        self.btnColorComment.setObjectName("btnColorComment")
        self.gridlayout5.addWidget(self.btnColorComment,4,3,1,1)

        self.lblsupportteam_3 = QtGui.QLabel(self.frame2)
        self.lblsupportteam_3.setObjectName("lblsupportteam_3")
        self.gridlayout5.addWidget(self.lblsupportteam_3,5,0,1,1)

        self.lblTM = QtGui.QLabel(self.frame2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(1))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTM.sizePolicy().hasHeightForWidth())
        self.lblTM.setSizePolicy(sizePolicy)
        self.lblTM.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblTM.setObjectName("lblTM")
        self.gridlayout5.addWidget(self.lblTM,5,1,1,1)

        self.bntFontTM = QtGui.QPushButton(self.frame2)
        self.bntFontTM.setObjectName("bntFontTM")
        self.gridlayout5.addWidget(self.bntFontTM,5,2,1,1)

        self.btnColorTM = QtGui.QPushButton(self.frame2)
        self.btnColorTM.setObjectName("btnColorTM")
        self.gridlayout5.addWidget(self.btnColorTM,5,3,1,1)

        self.bntFontGlossary = QtGui.QPushButton(self.frame2)
        self.bntFontGlossary.setObjectName("bntFontGlossary")
        self.gridlayout5.addWidget(self.bntFontGlossary,6,2,1,1)

        self.lblsupportteam_4 = QtGui.QLabel(self.frame2)
        self.lblsupportteam_4.setObjectName("lblsupportteam_4")
        self.gridlayout5.addWidget(self.lblsupportteam_4,6,0,1,1)

        self.lblGlossary = QtGui.QLabel(self.frame2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(1))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblGlossary.sizePolicy().hasHeightForWidth())
        self.lblGlossary.setSizePolicy(sizePolicy)
        self.lblGlossary.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblGlossary.setObjectName("lblGlossary")
        self.gridlayout5.addWidget(self.lblGlossary,6,1,1,1)

        self.lblOverViewHeader = QtGui.QLabel(self.frame2)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(1))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOverViewHeader.sizePolicy().hasHeightForWidth())
        self.lblOverViewHeader.setSizePolicy(sizePolicy)
        self.lblOverViewHeader.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblOverViewHeader.setObjectName("lblOverViewHeader")
        self.gridlayout5.addWidget(self.lblOverViewHeader,0,1,1,1)
        self.gridlayout4.addWidget(self.frame2,2,0,1,1)

        spacerItem1 = QtGui.QSpacerItem(20,40,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.gridlayout4.addItem(spacerItem1,3,0,1,1)
        self.stackedWidget.addWidget(self.interface)

        self.TM_Glossary  = QtGui.QWidget()
        self.TM_Glossary .setObjectName("TM_Glossary ")

        self.gridlayout6 = QtGui.QGridLayout(self.TM_Glossary )
        self.gridlayout6.setMargin(9)
        self.gridlayout6.setSpacing(6)
        self.gridlayout6.setObjectName("gridlayout6")

        spacerItem2 = QtGui.QSpacerItem(20,40,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.gridlayout6.addItem(spacerItem2,7,0,1,1)

        self.frame_4 = QtGui.QFrame(self.TM_Glossary )

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(5))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setObjectName("frame_4")

        self.gridlayout7 = QtGui.QGridLayout(self.frame_4)
        self.gridlayout7.setMargin(0)
        self.gridlayout7.setSpacing(6)
        self.gridlayout7.setObjectName("gridlayout7")

        self.chbDetectTerm = QtGui.QCheckBox(self.frame_4)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chbDetectTerm.sizePolicy().hasHeightForWidth())
        self.chbDetectTerm.setSizePolicy(sizePolicy)
        self.chbDetectTerm.setObjectName("chbDetectTerm")
        self.gridlayout7.addWidget(self.chbDetectTerm,3,0,1,1)

        self.frame_5 = QtGui.QFrame(self.frame_4)
        self.frame_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")

        self.chbSuggestTranslation = QtGui.QCheckBox(self.frame_5)
        self.chbSuggestTranslation.setGeometry(QtCore.QRect(0,30,223,21))
        self.chbSuggestTranslation.setObjectName("chbSuggestTranslation")

        self.chbAddNewTerm = QtGui.QCheckBox(self.frame_5)
        self.chbAddNewTerm.setGeometry(QtCore.QRect(0,1,382,16))

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chbAddNewTerm.sizePolicy().hasHeightForWidth())
        self.chbAddNewTerm.setSizePolicy(sizePolicy)
        self.chbAddNewTerm.setObjectName("chbAddNewTerm")
        self.gridlayout7.addWidget(self.frame_5,4,0,1,1)

        self.chbMatchTerm = QtGui.QCheckBox(self.frame_4)
        self.chbMatchTerm.setObjectName("chbMatchTerm")
        self.gridlayout7.addWidget(self.chbMatchTerm,2,0,1,1)

        self.chbChangeTerm = QtGui.QCheckBox(self.frame_4)
        self.chbChangeTerm.setObjectName("chbChangeTerm")
        self.gridlayout7.addWidget(self.chbChangeTerm,1,0,1,1)

        self.chbAutoIdentTerm = QtGui.QCheckBox(self.frame_4)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chbAutoIdentTerm.sizePolicy().hasHeightForWidth())
        self.chbAutoIdentTerm.setSizePolicy(sizePolicy)
        self.chbAutoIdentTerm.setObjectName("chbAutoIdentTerm")
        self.gridlayout7.addWidget(self.chbAutoIdentTerm,0,0,1,1)
        self.gridlayout6.addWidget(self.frame_4,6,0,1,1)

        spacerItem3 = QtGui.QSpacerItem(20,20,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Minimum)
        self.gridlayout6.addItem(spacerItem3,3,0,1,1)

        self.line_3 = QtGui.QFrame(self.TM_Glossary )
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridlayout6.addWidget(self.line_3,1,0,1,1)

        self.frame_3 = QtGui.QFrame(self.TM_Glossary )

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(5))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setObjectName("frame_3")

        self.gridlayout8 = QtGui.QGridLayout(self.frame_3)
        self.gridlayout8.setMargin(0)
        self.gridlayout8.setSpacing(6)
        self.gridlayout8.setObjectName("gridlayout8")

        self.chbAutoTranslate = QtGui.QCheckBox(self.frame_3)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chbAutoTranslate.sizePolicy().hasHeightForWidth())
        self.chbAutoTranslate.setSizePolicy(sizePolicy)
        self.chbAutoTranslate.setObjectName("chbAutoTranslate")
        self.gridlayout8.addWidget(self.chbAutoTranslate,0,0,1,1)

        self.chbIgnoreFuzzy = QtGui.QCheckBox(self.frame_3)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chbIgnoreFuzzy.sizePolicy().hasHeightForWidth())
        self.chbIgnoreFuzzy.setSizePolicy(sizePolicy)
        self.chbIgnoreFuzzy.setObjectName("chbIgnoreFuzzy")
        self.gridlayout8.addWidget(self.chbIgnoreFuzzy,1,0,1,1)

        self.chbAddTraslation = QtGui.QCheckBox(self.frame_3)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chbAddTraslation.sizePolicy().hasHeightForWidth())
        self.chbAddTraslation.setSizePolicy(sizePolicy)
        self.chbAddTraslation.setObjectName("chbAddTraslation")
        self.gridlayout8.addWidget(self.chbAddTraslation,3,0,1,1)

        self.chbEditTraslation = QtGui.QCheckBox(self.frame_3)
        self.chbEditTraslation.setObjectName("chbEditTraslation")
        self.gridlayout8.addWidget(self.chbEditTraslation,2,0,1,1)
        self.gridlayout6.addWidget(self.frame_3,2,0,1,1)

        self.label_5 = QtGui.QLabel(self.TM_Glossary )

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(5))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)

        font = QtGui.QFont(self.label_5.font())
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridlayout6.addWidget(self.label_5,0,0,1,1)

        self.label_6 = QtGui.QLabel(self.TM_Glossary )

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(5))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)

        font = QtGui.QFont(self.label_6.font())
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridlayout6.addWidget(self.label_6,4,0,1,1)

        self.line_4 = QtGui.QFrame(self.TM_Glossary )
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridlayout6.addWidget(self.line_4,5,0,1,1)
        self.stackedWidget.addWidget(self.TM_Glossary )

        self.save = QtGui.QWidget()
        self.save.setObjectName("save")

        self.gridlayout9 = QtGui.QGridLayout(self.save)
        self.gridlayout9.setMargin(9)
        self.gridlayout9.setSpacing(6)
        self.gridlayout9.setObjectName("gridlayout9")

        self.frame_6 = QtGui.QFrame(self.save)
        self.frame_6.setObjectName("frame_6")

        self.gridlayout10 = QtGui.QGridLayout(self.frame_6)
        self.gridlayout10.setMargin(0)
        self.gridlayout10.setSpacing(6)
        self.gridlayout10.setObjectName("gridlayout10")

        self.chkHeaderAuto = QtGui.QCheckBox(self.frame_6)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkHeaderAuto.sizePolicy().hasHeightForWidth())
        self.chkHeaderAuto.setSizePolicy(sizePolicy)
        self.chkHeaderAuto.setChecked(True)
        self.chkHeaderAuto.setObjectName("chkHeaderAuto")
        self.gridlayout10.addWidget(self.chkHeaderAuto,0,0,1,1)
        self.gridlayout9.addWidget(self.frame_6,2,0,1,1)

        spacerItem4 = QtGui.QSpacerItem(20,40,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.gridlayout9.addItem(spacerItem4,3,0,1,1)

        self.label_7 = QtGui.QLabel(self.save)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(5))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)

        font = QtGui.QFont(self.label_7.font())
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridlayout9.addWidget(self.label_7,0,0,1,1)

        self.line_5 = QtGui.QFrame(self.save)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridlayout9.addWidget(self.line_5,1,0,1,1)
        self.stackedWidget.addWidget(self.save)

        self.page = QtGui.QWidget()
        self.page.setObjectName("page")

        self.gridlayout11 = QtGui.QGridLayout(self.page)
        self.gridlayout11.setMargin(9)
        self.gridlayout11.setSpacing(6)
        self.gridlayout11.setObjectName("gridlayout11")

        spacerItem5 = QtGui.QSpacerItem(20,40,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.gridlayout11.addItem(spacerItem5,3,0,1,1)

        self.frame_7 = QtGui.QFrame(self.page)
        self.frame_7.setObjectName("frame_7")

        self.gridlayout12 = QtGui.QGridLayout(self.frame_7)
        self.gridlayout12.setMargin(0)
        self.gridlayout12.setSpacing(6)
        self.gridlayout12.setObjectName("gridlayout12")

        self.chkCursorHome = QtGui.QCheckBox(self.frame_7)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkCursorHome.sizePolicy().hasHeightForWidth())
        self.chkCursorHome.setSizePolicy(sizePolicy)
        self.chkCursorHome.setChecked(True)
        self.chkCursorHome.setObjectName("chkCursorHome")
        self.gridlayout12.addWidget(self.chkCursorHome,0,0,1,1)
        self.gridlayout11.addWidget(self.frame_7,2,0,1,1)

        self.line_6 = QtGui.QFrame(self.page)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridlayout11.addWidget(self.line_6,1,0,1,1)

        self.label_8 = QtGui.QLabel(self.page)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(5))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)

        font = QtGui.QFont(self.label_8.font())
        font.setWeight(75)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridlayout11.addWidget(self.label_8,0,0,1,1)
        self.stackedWidget.addWidget(self.page)
        self.gridlayout1.addWidget(self.stackedWidget,0,1,1,1)

        self.listWidget = QtGui.QListWidget(self.frame)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(1),QtGui.QSizePolicy.Policy(1))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMinimumSize(QtCore.QSize(0,0))
        self.listWidget.setMaximumSize(QtCore.QSize(100,16777215))
        self.listWidget.setResizeMode(QtGui.QListView.Adjust)
        self.listWidget.setLayoutMode(QtGui.QListView.SinglePass)
        self.listWidget.setModelColumn(0)
        self.listWidget.setObjectName("listWidget")
        self.gridlayout1.addWidget(self.listWidget,0,0,1,1)
        self.gridlayout.addWidget(self.frame,0,0,1,3)

        spacerItem6 = QtGui.QSpacerItem(40,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem6,1,0,1,1)

        self.okButton = QtGui.QPushButton(frmPreference)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(1),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.okButton.sizePolicy().hasHeightForWidth())
        self.okButton.setSizePolicy(sizePolicy)
        self.okButton.setObjectName("okButton")
        self.gridlayout.addWidget(self.okButton,1,1,1,1)

        self.cancelButton = QtGui.QPushButton(frmPreference)
        self.cancelButton.setObjectName("cancelButton")
        self.gridlayout.addWidget(self.cancelButton,1,2,1,1)

        self.retranslateUi(frmPreference)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmPreference)
        frmPreference.setTabOrder(self.listWidget,self.UserName)
        frmPreference.setTabOrder(self.UserName,self.EmailAddress)
        frmPreference.setTabOrder(self.EmailAddress,self.cbxLanguageCode)
        frmPreference.setTabOrder(self.cbxLanguageCode,self.lineFullLang)
        frmPreference.setTabOrder(self.lineFullLang,self.SupportTeam)
        frmPreference.setTabOrder(self.SupportTeam,self.spinBox)
        frmPreference.setTabOrder(self.spinBox,self.lineEqaution)
        frmPreference.setTabOrder(self.lineEqaution,self.bntFontOverviewHeader)
        frmPreference.setTabOrder(self.bntFontOverviewHeader,self.bntFontOverview)
        frmPreference.setTabOrder(self.bntFontOverview,self.btnColorOverview)
        frmPreference.setTabOrder(self.btnColorOverview,self.bntFontSource)
        frmPreference.setTabOrder(self.bntFontSource,self.btnColorSource)
        frmPreference.setTabOrder(self.btnColorSource,self.bntFontTarget)
        frmPreference.setTabOrder(self.bntFontTarget,self.btnColorTarget)
        frmPreference.setTabOrder(self.btnColorTarget,self.bntFontComment)
        frmPreference.setTabOrder(self.bntFontComment,self.btnColorComment)
        frmPreference.setTabOrder(self.btnColorComment,self.bntFontTM)
        frmPreference.setTabOrder(self.bntFontTM,self.btnColorTM)
        frmPreference.setTabOrder(self.btnColorTM,self.bntFontGlossary)
        frmPreference.setTabOrder(self.bntFontGlossary,self.btnColorGlossary)
        frmPreference.setTabOrder(self.btnColorGlossary,self.bntAdjustAllFont)
        frmPreference.setTabOrder(self.bntAdjustAllFont,self.bntDefaultsFont)
        frmPreference.setTabOrder(self.bntDefaultsFont,self.bntDefaultsColor)
        frmPreference.setTabOrder(self.bntDefaultsColor,self.chbAutoTranslate)
        frmPreference.setTabOrder(self.chbAutoTranslate,self.chbIgnoreFuzzy)
        frmPreference.setTabOrder(self.chbIgnoreFuzzy,self.chbEditTraslation)
        frmPreference.setTabOrder(self.chbEditTraslation,self.chbAddTraslation)
        frmPreference.setTabOrder(self.chbAddTraslation,self.chbAutoIdentTerm)
        frmPreference.setTabOrder(self.chbAutoIdentTerm,self.chbChangeTerm)
        frmPreference.setTabOrder(self.chbChangeTerm,self.chbMatchTerm)
        frmPreference.setTabOrder(self.chbMatchTerm,self.chbDetectTerm)
        frmPreference.setTabOrder(self.chbDetectTerm,self.chbAddNewTerm)
        frmPreference.setTabOrder(self.chbAddNewTerm,self.chbSuggestTranslation)
        frmPreference.setTabOrder(self.chbSuggestTranslation,self.chkHeaderAuto)
        frmPreference.setTabOrder(self.chkHeaderAuto,self.chkCursorHome)
        frmPreference.setTabOrder(self.chkCursorHome,self.okButton)
        frmPreference.setTabOrder(self.okButton,self.cancelButton)

    def tr(self, string):
        return QtGui.QApplication.translate("frmPreference", string, None, QtGui.QApplication.UnicodeUTF8)

    def retranslateUi(self, frmPreference):
        frmPreference.setWindowTitle(self.tr("Preferences"))
        self.spinBox.setWhatsThis(self.tr("<h3>Singular/Plural forms</h3>Set plural forms for a specific language. Pootling try to set this value for you. If no information provided, you should fill up by yourself or leave it blank if you are not sure."))
        self.lineEqaution.setWhatsThis(self.tr("<h3>Plural equation</h3>Set plural equation for a specific language. Pootling tries to set this value for you. If no information provided, you should fill up by yourself or leave it blank if you are not sure."))
        self.label_3.setText(self.tr("Number of singular/plural forms:"))
        self.label_2.setText(self.tr("Plural equation:"))
        self.label1.setText(self.tr("User name"))
        self.UserName.setWhatsThis(self.tr("<h3>User Name</h3>Type your full name here."))
        self.EmailAddress.setWhatsThis(self.tr("<h3>Email Address</h3>Type your own email."))
        self.label2.setText(self.tr("Email address"))
        self.lineFullLang.setWhatsThis(self.tr("<h3>Language name</h3>Your full language name, for example, \"Khmer\", an official language of Cambodia."))
        self.cbxLanguageCode.setWhatsThis(self.tr("<h3>Language Code</h3>Choose your own language code. If your language code isn\'t in the list, please type in by yourself. Pootling will try to set the correct language name, number of singular/plural form and plural equation for you."))
        self.label4.setText(self.tr("Language Code"))
        self.label3.setText(self.tr("Language name"))
        self.SupportTeam.setWhatsThis(self.tr("<h3>Support</h3>Type support email address."))
        self.label5.setText(self.tr("Support team"))
        self.label.setText(self.tr("Personal Information"))
        self.label_4.setText(self.tr("Font & Color"))
        self.bntAdjustAllFont.setText(self.tr("Adjust All Fonts"))
        self.bntDefaultsFont.setWhatsThis(self.tr("<h3>Defaults Font</h3>Once this button is clicked, Overview, Source, Target and Comment will be set to default font, Serif, 10."))
        self.bntDefaultsFont.setText(self.tr("Default Font"))
        self.bntDefaultsColor.setWhatsThis(self.tr("<h3>Defaults Color</h3>Once this button is clicked, Overview, Source, Target and Comment will be set to default color, black."))
        self.bntDefaultsColor.setText(self.tr("Default Color"))
        self.btnColorGlossary.setWhatsThis(self.tr("<h3>Comment Color</h3>Click this button  will show up a color dialog box where you can choose color for comment text."))
        self.btnColorGlossary.setText(self.tr("Color"))
        self.lblTarget.setToolTip(self.tr("Target Sample"))
        self.lblTarget.setWhatsThis(self.tr("<h3>Target Sample</h3>This lable displayed the current font name, style, size and color sample of target dock widget."))
        self.lblSource.setToolTip(self.tr("Source Sample"))
        self.lblSource.setWhatsThis(self.tr("<h3>Source Sample</h3>This lable displayed the current font name, style, size and color sample of source dock widget."))
        self.lblOverView.setToolTip(self.tr("Overview Sample"))
        self.lblOverView.setWhatsThis(self.tr("<h3>Overview Sample</h3>This lable displayed the current font name, style, size and color sample of overview dock widget."))
        self.bntFontOverviewHeader.setWhatsThis(self.tr("<h3>Overview Header Font</h3>Click this button  will show up a font dialog box where you can select fontname, style and size for overview header text."))
        self.bntFontOverviewHeader.setText(self.tr("Font"))
        self.bntFontOverview.setWhatsThis(self.tr("<h3>Overview Font</h3>Click this button  will show up a font dialog box where you can select fontname, style and size for overview text."))
        self.bntFontOverview.setText(self.tr("Font"))
        self.bntFontSource.setWhatsThis(self.tr("<h3>Source Font</h3>Click this button  will show up a font dialog box where you can select fontname, style and size for source text."))
        self.bntFontSource.setText(self.tr("Font"))
        self.bntFontTarget.setWhatsThis(self.tr("<h3>Target Font</h3>Click this button  will show up a font dialog box where you can select fontname, style and size for target text."))
        self.bntFontTarget.setText(self.tr("Font"))
        self.btnColorOverview.setWhatsThis(self.tr("<h3>Overview Color</h3>Click this button  will show up a color dialog box where you can choose color for overview text."))
        self.btnColorOverview.setText(self.tr("Color"))
        self.btnColorSource.setWhatsThis(self.tr("<h3>Source Color</h3>Click this button  will show up a color dialog box where you can choose color for source text."))
        self.btnColorSource.setText(self.tr("Color"))
        self.btnColorTarget.setWhatsThis(self.tr("<h3>Target Color</h3>Click this button  will show up a color dialog box where you can choose color for target text."))
        self.btnColorTarget.setText(self.tr("Color"))
        self.label4_3.setText(self.tr("Target"))
        self.label2_5.setText(self.tr("Overview"))
        self.label2_4.setText(self.tr("Overview header"))
        self.Source_2.setText(self.tr("Source"))
        self.lblsupportteam_2.setText(self.tr("Comment"))
        self.lblComment.setToolTip(self.tr("Comment Sample"))
        self.lblComment.setWhatsThis(self.tr("<h3>Comment Sample</h3>This lable displayed the current font name, style, size and color sample of comment dock widget."))
        self.bntFontComment.setWhatsThis(self.tr("<h3>Comment Font</h3>Click this button  will show up a font dialog box where you can select fontname, style and size for comment text."))
        self.bntFontComment.setText(self.tr("Font"))
        self.btnColorComment.setWhatsThis(self.tr("<h3>Comment Color</h3>Click this button  will show up a color dialog box where you can choose color for comment text."))
        self.btnColorComment.setText(self.tr("Color"))
        self.lblsupportteam_3.setText(self.tr("TM Lookup"))
        self.lblTM.setToolTip(self.tr("Comment Sample"))
        self.lblTM.setWhatsThis(self.tr("<h3>Comment Sample</h3>This lable displayed the current font name, style, size and color sample of comment dock widget."))
        self.bntFontTM.setWhatsThis(self.tr("<h3>Comment Font</h3>Click this button  will show up a font dialog box where you can select fontname, style and size for comment text."))
        self.bntFontTM.setText(self.tr("Font"))
        self.btnColorTM.setWhatsThis(self.tr("<h3>Comment Color</h3>Click this button  will show up a color dialog box where you can choose color for comment text."))
        self.btnColorTM.setText(self.tr("Color"))
        self.bntFontGlossary.setWhatsThis(self.tr("<h3>Comment Font</h3>Click this button  will show up a font dialog box where you can select fontname, style and size for comment text."))
        self.bntFontGlossary.setText(self.tr("Font"))
        self.lblsupportteam_4.setText(self.tr("Glossary Lookup"))
        self.lblGlossary.setToolTip(self.tr("Comment Sample"))
        self.lblGlossary.setWhatsThis(self.tr("<h3>Comment Sample</h3>This lable displayed the current font name, style, size and color sample of comment dock widget."))
        self.lblOverViewHeader.setToolTip(self.tr("Overview Header Sample"))
        self.lblOverViewHeader.setWhatsThis(self.tr("<h3>Overview Header Sample</h3>This lable displayed the current font name, style, size and color sample of overview header dock widget."))
        self.chbDetectTerm.setText(self.tr("Detect new terminology"))
        self.chbSuggestTranslation.setText(self.tr("Allow translation suggestion from TM"))
        self.chbAddNewTerm.setText(self.tr("Add new terminology to glossary"))
        self.chbMatchTerm.setText(self.tr("Alert if the terminology\'s translation doesn\'t match"))
        self.chbChangeTerm.setText(self.tr("Possible to change translation of terminology in glossary"))
        self.chbAutoIdentTerm.setWhatsThis(self.tr("<h3>Highlight glossary term</h3> This option is recommended to be used. You will see the green and underlined terms in TUview ( source section). It indicates that those terms are in Glossary."))
        self.chbAutoIdentTerm.setText(self.tr("Highlight glossary term in Detail view"))
        self.chbAutoTranslate.setWhatsThis(self.tr("<h3>Lookup translation in TM</h3> If this option is checked, you will get a TM Lookup Table soon after clicking on OK button. From that table, you will see the relevent translated unit(s) that had already been built and stored in memory."))
        self.chbAutoTranslate.setText(self.tr("Lookup translation in TM"))
        self.chbIgnoreFuzzy.setWhatsThis(self.tr("<h3>Ignore Fuzzy Strings</h3> If this option is checked, the fuzzy string will not be searching for from the Translation Memory."))
        self.chbIgnoreFuzzy.setText(self.tr("Don\'t lookup fuzzy strings"))
        self.chbAddTraslation.setWhatsThis(self.tr("<h3>Add new Translation to Translation Memory</h3> If this option is checked, all new translation units will be added to the Translation Memory for later use after saving."))
        self.chbAddTraslation.setText(self.tr("Add new translation to TM"))
        self.chbEditTraslation.setText(self.tr("Possible to change translation in TM"))
        self.label_5.setText(self.tr("Options for Using Translation Memory"))
        self.label_6.setText(self.tr("Options for Using Glossary"))
        self.chkHeaderAuto.setWhatsThis(self.tr("<h3>Update header on save</h3>Check this opton to automatically have your header updated while saving. The information will be querried from Personalize tab. "))
        self.chkHeaderAuto.setText(self.tr("Update header on save"))
        self.label_7.setText(self.tr("Options for Saving File"))
        self.chkCursorHome.setWhatsThis(self.tr("<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
        "p, li { white-space: pre-wrap; }\n"
        "</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
        "<p style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:large; font-weight:600;\"><span style=\" font-size:large;\">Options for Editor</span></p>\n"
        "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Set to move cursor to the beginning of string after copied source to target, otherwise keep the cursor untouched.</p></body></html>"))
        self.chkCursorHome.setText(self.tr("Move cursor to the beginning of string after copied source to target."))
        self.label_8.setText(self.tr("Options for Editor"))
        self.okButton.setText(self.tr("&OK"))
        self.cancelButton.setText(self.tr("&Cancel"))


if __name__ == "__main__":
    app = QtGui.QApplication(sys.argv)
    frmPreference = QtGui.QDialog()
    ui = Ui_frmPreference()
    ui.setupUi(frmPreference)
    frmPreference.show()
    sys.exit(app.exec_())
