# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-22 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='object ID')),
                ('key', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Revision key')),
                ('value', models.CharField(default='', max_length=255, verbose_name='Revision hash or numeric marker')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_type_set_for_revision', to='contenttypes.ContentType', verbose_name='content type')),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
                'db_table': 'pootle_revision',
            },
        ),
        migrations.AlterUniqueTogether(
            name='revision',
            unique_together=set([('content_type', 'object_id', 'key')]),
        ),
        migrations.AlterIndexTogether(
            name='revision',
            index_together=set([('object_id', 'content_type', 'key')]),
        ),
    ]
