# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-19 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_data', '0003_index_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storedata',
            name='last_updated_unit',
        ),
        migrations.RemoveField(
            model_name='tpdata',
            name='last_updated_unit',
        ),
    ]
