# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-08 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_data', '0005_add_store_and_tp_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storechecksdata',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_data', to='pootle_store.Store'),
        ),
        migrations.AlterField(
            model_name='storedata',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='pootle_store.Store'),
        ),
        migrations.AlterField(
            model_name='tpchecksdata',
            name='tp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_data', to='pootle_translationproject.TranslationProject'),
        ),
        migrations.AlterField(
            model_name='tpdata',
            name='tp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='pootle_translationproject.TranslationProject'),
        ),
    ]
