# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_data', '0007_add_store_and_tp_data_again'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedata',
            name='last_created_unit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_created_for_storedata', to='pootle_store.Unit'),
        ),
        migrations.AlterField(
            model_name='storedata',
            name='last_submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storedata_stats_data', to='pootle_statistics.Submission'),
        ),
        migrations.AlterField(
            model_name='tpdata',
            name='last_created_unit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_created_for_tpdata', to='pootle_store.Unit'),
        ),
        migrations.AlterField(
            model_name='tpdata',
            name='last_submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tpdata_stats_data', to='pootle_statistics.Submission'),
        ),
    ]
