# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-02 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_store', '0030_remove_extra_indeces'),
        ('pootle_translationproject', '0007_set_tp_base_manager_name'),
        ('pootle_data', '0008_keep_data_on_delete'),
    ]
    operations = [
        migrations.AlterField(
            model_name='storechecksdata',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='tpchecksdata',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='storechecksdata',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='tpchecksdata',
            unique_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='storechecksdata',
            index_together=set([('name', 'category')]),
        ),
        migrations.AlterIndexTogether(
            name='tpchecksdata',
            index_together=set([('name', 'category')]),
        ),
        migrations.AlterUniqueTogether(
            name='storechecksdata',
            unique_together=set([('store', 'category', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='tpchecksdata',
            unique_together=set([('tp', 'category', 'name')]),
        ),
        migrations.AlterField(
            model_name='storechecksdata',
            name='store',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='check_data', to='pootle_store.Store'),
        ),
        migrations.AlterField(
            model_name='tpchecksdata',
            name='tp',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='check_data', to='pootle_translationproject.TranslationProject'),
        ),
    ]
