# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_data', '0009_remove_extra_indeces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedata',
            name='max_unit_revision',
            field=models.IntegerField(blank=True, db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='tpdata',
            name='max_unit_revision',
            field=models.IntegerField(blank=True, db_index=True, default=0),
        ),
    ]
