#!/bin/bash
# this is a script for running repeated tests on different hosts for bugday
timestamp=`date '+%Y%m%d-%H%M'`
bugday=`date '+%Y%m%d'`
hostname=`hostname`
dest=sourceforge:translate/html/bugdays/${bugday}
scriptdir="`dirname "$0"`"
srcdir="`cd "${scriptdir}" ; cd .. ; pwd`"

logfile=${hostname}-${timestamp}.log

versions=$(Pootle/PootleServer --version)

cd "$srcdir"
mkdir -p testlogs
echo ${timestamp} ${logfile}
(
  echo -n "automated test at ${timestamp} on "
  uname -snmo
  echo
  echo -n "With "
  python -V
  echo "branches:"
  pootlebranch=`svn info Pootle|grep URL|sed -e 's/URL: //' |sed -e 's/\/\/.*@/\/\//'`
  toolkitbranch=`svn info translate|grep URL|sed -e 's/URL: //' |sed -e 's/\/\/.*@/\/\//'`
  echo "Pootle is on branch:" $pootlebranch
  echo "Translate Toolkit is on branch:" $toolkitbranch
  echo
  echo "Versions:"
  echo $versions
  echo
  echo "update:"
  echo "-------"
  svn up
  echo "local changes:"
  echo "--------------"
  svn diff
  echo "running tests:"
  echo "--------------"
  py.test translate Pootle
  echo
  echo "done"
) 2>&1 | tee testlogs/${logfile}
scp -p testlogs/${logfile} ${dest}/$logfile

