All you need to know
--------------------

The following pages cover the documentation of Pootle from a wide variety of
perspectives, server administrator's, and developer's view.

.. toctree::
   :maxdepth: 2

   features/index

.. toctree::
   :maxdepth: 1

   server/installation
   server/upgrading
   server/index
   developers/index


.. _notes:

Additional Notes
----------------

.. toctree::
   :maxdepth: 1

   releases/index
   license
