All you need to know
--------------------

The following pages cover the documentation of Pootle from a wide variety of
perspectives, including user's, server administrator's, and developer's view.

.. toctree::
   :maxdepth: 2

   users/index
   features/index
   server/index
   developers/index
   api/index


.. _notes:

Additional Notes
----------------

.. toctree::
   :maxdepth: 1

   changelog
   external_docs
   license
