Using Pootle
------------

.. toctree::
   :maxdepth: 2

   getting_started
   translating


Features
--------

.. toctree::
   :maxdepth: 2


Administering a server
----------------------

.. toctree::
   :maxdepth: 2

   installation
   upgrading
   changelog


Developers
----------

If you are a developer and are willing to hack on Pootle, make sure to
read through this part.

.. toctree::
   :maxdepth: 2

   styleguide


Additional Notes
----------------

.. toctree::
   :maxdepth: 2

   license
