#!/bin/bash

set -e

if [ ! -z "$BUILD_INSTALL_PRE" ];
 then
     $BUILD_INSTALL_PRE;
fi

if [ ! -z "$BUILD_INSTALL_PKGS" ];
 then
     apt-get update -qq
     apt-get install -qq -y \
             --no-install-recommends \
             $BUILD_INSTALL_PKGS;
     apt-get clean
     rm -rf /var/lib/apt/lists/* /var/tmp/*
fi
