(function(){function diff_match_patch(){function a(){for(var b=0,c=1,d=2;c!=d;){b++;c=d;d<<=1}return b}this.Diff_Timeout=1;this.Diff_EditCost=4;this.Diff_DualThreshold=32;this.Match_Threshold=0.5;this.Match_Distance=1E3;this.Patch_DeleteThreshold=0.5;this.Patch_Margin=4;this.Match_MaxBits=a()}
diff_match_patch.prototype.diff_main=function(a,b,c){if(a==null||b==null)throw Error("Null input. (diff_main)");if(a==b){if(a)return[[0,a]];return[]}if(typeof c=="undefined")c=true;var d=c,e=this.diff_commonPrefix(a,b);c=a.substring(0,e);a=a.substring(e);b=b.substring(e);e=this.diff_commonSuffix(a,b);var f=a.substring(a.length-e);a=a.substring(0,a.length-e);b=b.substring(0,b.length-e);a=this.diff_compute(a,b,d);c&&a.unshift([0,c]);f&&a.push([0,f]);this.diff_cleanupMerge(a);return a};
diff_match_patch.prototype.diff_compute=function(a,b,c){var d;if(!a)return[[1,b]];if(!b)return[[-1,a]];d=a.length>b.length?a:b;var e=a.length>b.length?b:a,f=d.indexOf(e);if(f!=-1){d=[[1,d.substring(0,f)],[0,e],[1,d.substring(f+e.length)]];if(a.length>b.length)d[0][0]=d[2][0]=-1;return d}if(d=this.diff_halfMatch(a,b)){var g=d[0];a=d[1];e=d[2];b=d[3];d=d[4];g=this.diff_main(g,e,c);c=this.diff_main(a,b,c);return g.concat([[0,d]],c)}if(c&&(a.length<100||b.length<100))c=false;if(c){g=this.diff_linesToChars(a,
b);a=g[0];b=g[1];g=g[2]}(d=this.diff_map(a,b))||(d=[[-1,a],[1,b]]);if(c){this.diff_charsToLines(d,g);this.diff_cleanupSemantic(d);d.push([0,""]);b=a=c=0;for(e=g="";c<d.length;){switch(d[c][0]){case 1:b++;e+=d[c][1];break;case -1:a++;g+=d[c][1];break;case 0:if(a>=1&&b>=1){g=this.diff_main(g,e,false);d.splice(c-a-b,a+b);c=c-a-b;for(a=g.length-1;a>=0;a--)d.splice(c,0,g[a]);c+=g.length}a=b=0;e=g=""}c++}d.pop()}return d};
diff_match_patch.prototype.diff_linesToChars=function(a,b){function c(h){for(var j="",i=0,k=-1,l=d.length;k<h.length-1;){k=h.indexOf("\n",i);if(k==-1)k=h.length-1;var m=h.substring(i,k+1);i=k+1;if(e.hasOwnProperty?e.hasOwnProperty(m):e[m]!==undefined)j+=String.fromCharCode(e[m]);else{j+=String.fromCharCode(l);e[m]=l;d[l++]=m}}return j}var d=[],e={};d[0]="";var f=c(a),g=c(b);return[f,g,d]};
diff_match_patch.prototype.diff_charsToLines=function(a,b){for(var c=0;c<a.length;c++){for(var d=a[c][1],e=[],f=0;f<d.length;f++)e[f]=b[d.charCodeAt(f)];a[c][1]=e.join("")}};
diff_match_patch.prototype.diff_map=function(a,b){var c=(new Date).getTime()+this.Diff_Timeout*1E3,d=a.length,e=b.length,f=d+e-1,g=this.Diff_DualThreshold*2<f,h=[],j=[],i={},k={};i[1]=0;k[1]=0;for(var l,m,n,o={},s=false,r=(d+e)%2,q=0;q<f;q++){if(this.Diff_Timeout>0&&(new Date).getTime()>c)break;h[q]={};for(var p=-q;p<=q;p+=2){l=p==-q||p!=q&&i[p-1]<i[p+1]?i[p+1]:i[p-1]+1;m=l-p;if(g){n=l+","+m;if(r&&o[n]!==undefined)s=true;r||(o[n]=q)}for(;!s&&l<d&&m<e&&a.charAt(l)==b.charAt(m);){l++;m++;if(g){n=l+
","+m;if(r&&o[n]!==undefined)s=true;r||(o[n]=q)}}i[p]=l;h[q][l+","+m]=true;if(l==d&&m==e)return this.diff_path1(h,a,b);else if(s){j=j.slice(0,o[n]+1);c=this.diff_path1(h,a.substring(0,l),b.substring(0,m));return c.concat(this.diff_path2(j,a.substring(l),b.substring(m)))}}if(g){j[q]={};for(p=-q;p<=q;p+=2){l=p==-q||p!=q&&k[p-1]<k[p+1]?k[p+1]:k[p-1]+1;m=l-p;n=d-l+","+(e-m);if(!r&&o[n]!==undefined)s=true;if(r)o[n]=q;for(;!s&&l<d&&m<e&&a.charAt(d-l-1)==b.charAt(e-m-1);){l++;m++;n=d-l+","+(e-m);if(!r&&
o[n]!==undefined)s=true;if(r)o[n]=q}k[p]=l;j[q][l+","+m]=true;if(s){h=h.slice(0,o[n]+1);c=this.diff_path1(h,a.substring(0,d-l),b.substring(0,e-m));return c.concat(this.diff_path2(j,a.substring(d-l),b.substring(e-m)))}}}}return null};
diff_match_patch.prototype.diff_path1=function(a,b,c){for(var d=[],e=b.length,f=c.length,g=null,h=a.length-2;h>=0;h--)for(;;)if(a[h][e-1+","+f]!==undefined){e--;if(g===-1)d[0][1]=b.charAt(e)+d[0][1];else d.unshift([-1,b.charAt(e)]);g=-1;break}else if(a[h][e+","+(f-1)]!==undefined){f--;if(g===1)d[0][1]=c.charAt(f)+d[0][1];else d.unshift([1,c.charAt(f)]);g=1;break}else{e--;f--;if(b.charAt(e)!=c.charAt(f))throw Error("No diagonal.  Can't happen. (diff_path1)");if(g===0)d[0][1]=b.charAt(e)+d[0][1];else d.unshift([0,
b.charAt(e)]);g=0}return d};
diff_match_patch.prototype.diff_path2=function(a,b,c){for(var d=[],e=0,f=b.length,g=c.length,h=null,j=a.length-2;j>=0;j--)for(;;)if(a[j][f-1+","+g]!==undefined){f--;if(h===-1)d[e-1][1]+=b.charAt(b.length-f-1);else d[e++]=[-1,b.charAt(b.length-f-1)];h=-1;break}else if(a[j][f+","+(g-1)]!==undefined){g--;if(h===1)d[e-1][1]+=c.charAt(c.length-g-1);else d[e++]=[1,c.charAt(c.length-g-1)];h=1;break}else{f--;g--;if(b.charAt(b.length-f-1)!=c.charAt(c.length-g-1))throw Error("No diagonal.  Can't happen. (diff_path2)");if(h===
0)d[e-1][1]+=b.charAt(b.length-f-1);else d[e++]=[0,b.charAt(b.length-f-1)];h=0}return d};diff_match_patch.prototype.diff_commonPrefix=function(a,b){if(!a||!b||a.charAt(0)!=b.charAt(0))return 0;for(var c=0,d=Math.min(a.length,b.length),e=d,f=0;c<e;){if(a.substring(f,e)==b.substring(f,e))f=c=e;else d=e;e=Math.floor((d-c)/2+c)}return e};
diff_match_patch.prototype.diff_commonSuffix=function(a,b){if(!a||!b||a.charAt(a.length-1)!=b.charAt(b.length-1))return 0;for(var c=0,d=Math.min(a.length,b.length),e=d,f=0;c<e;){if(a.substring(a.length-e,a.length-f)==b.substring(b.length-e,b.length-f))f=c=e;else d=e;e=Math.floor((d-c)/2+c)}return e};
diff_match_patch.prototype.diff_commonOverlap=function(a,b){var c=a.length,d=b.length;if(c==0||d==0)return 0;if(c>d)a=a.substring(c-d);else if(c<d)b=b.substring(0,c);c=Math.min(c,d);if(a==b)return c;d=0;for(var e=1;;){var f=a.substring(c-e);f=b.indexOf(f);if(f==-1)return d;e+=f;if(f==0||a.substring(c-e)==b.substring(0,e)){d=e;e++}}};
diff_match_patch.prototype.diff_halfMatch=function(a,b){function c(i,k,l){for(var m=i.substring(l,l+Math.floor(i.length/4)),n=-1,o="",s,r,q,p;(n=k.indexOf(m,n+1))!=-1;){var t=f.diff_commonPrefix(i.substring(l),k.substring(n)),u=f.diff_commonSuffix(i.substring(0,l),k.substring(0,n));if(o.length<u+t){o=k.substring(n-u,n)+k.substring(n,n+t);s=i.substring(0,l-u);r=i.substring(l+t);q=k.substring(0,n-u);p=k.substring(n+t)}}return o.length>=i.length/2?[s,r,q,p,o]:null}var d=a.length>b.length?a:b,e=a.length>
b.length?b:a;if(d.length<4||e.length*2<d.length)return null;var f=this,g=c(d,e,Math.ceil(d.length/4));d=c(d,e,Math.ceil(d.length/2));var h;if(!g&&!d)return null;else h=d?g?g[4].length>d[4].length?g:d:d:g;var j;if(a.length>b.length){g=h[0];d=h[1];e=h[2];j=h[3]}else{e=h[0];j=h[1];g=h[2];d=h[3]}h=h[4];return[g,d,e,j,h]};
diff_match_patch.prototype.diff_cleanupSemantic=function(a){for(var b=false,c=[],d=0,e=null,f=0,g=0,h=0;f<a.length;){if(a[f][0]==0){c[d++]=f;g=h;h=0;e=a[f][1]}else{h+=a[f][1].length;if(e!==null&&e.length<=g&&e.length<=h){a.splice(c[d-1],0,[-1,e]);a[c[d-1]+1][0]=1;d--;d--;f=d>0?c[d-1]:-1;h=g=0;e=null;b=true}}f++}b&&this.diff_cleanupMerge(a);this.diff_cleanupSemanticLossless(a);for(f=1;f<a.length;){if(a[f-1][0]==-1&&a[f][0]==1){b=a[f-1][1];c=a[f][1];if(d=this.diff_commonOverlap(b,c)){a.splice(f,0,[0,
c.substring(0,d)]);a[f-1][1]=b.substring(0,b.length-d);a[f+1][1]=c.substring(d);f++}f++}f++}};
diff_match_patch.prototype.diff_cleanupSemanticLossless=function(a){function b(r,q){if(!r||!q)return 5;var p=0;if(r.charAt(r.length-1).match(c)||q.charAt(0).match(c)){p++;if(r.charAt(r.length-1).match(d)||q.charAt(0).match(d)){p++;if(r.charAt(r.length-1).match(e)||q.charAt(0).match(e)){p++;if(r.match(f)||q.match(g))p++}}}return p}for(var c=/[^a-zA-Z0-9]/,d=/\s/,e=/[\r\n]/,f=/\n\r?\n$/,g=/^\r?\n\r?\n/,h=1;h<a.length-1;){if(a[h-1][0]==0&&a[h+1][0]==0){var j=a[h-1][1],i=a[h][1],k=a[h+1][1],l=this.diff_commonSuffix(j,
i);if(l){var m=i.substring(i.length-l);j=j.substring(0,j.length-l);i=m+i.substring(0,i.length-l);k=m+k}l=j;m=i;for(var n=k,o=b(j,i)+b(i,k);i.charAt(0)===k.charAt(0);){j+=i.charAt(0);i=i.substring(1)+k.charAt(0);k=k.substring(1);var s=b(j,i)+b(i,k);if(s>=o){o=s;l=j;m=i;n=k}}if(a[h-1][1]!=l){if(l)a[h-1][1]=l;else{a.splice(h-1,1);h--}a[h][1]=m;if(n)a[h+1][1]=n;else{a.splice(h+1,1);h--}}}h++}};
diff_match_patch.prototype.diff_cleanupEfficiency=function(a){for(var b=false,c=[],d=0,e="",f=0,g=false,h=false,j=false,i=false;f<a.length;){if(a[f][0]==0){if(a[f][1].length<this.Diff_EditCost&&(j||i)){c[d++]=f;g=j;h=i;e=a[f][1]}else{d=0;e=""}j=i=false}else{if(a[f][0]==-1)i=true;else j=true;if(e&&(g&&h&&j&&i||e.length<this.Diff_EditCost/2&&g+h+j+i==3)){a.splice(c[d-1],0,[-1,e]);a[c[d-1]+1][0]=1;d--;e="";if(g&&h){j=i=true;d=0}else{d--;f=d>0?c[d-1]:-1;j=i=false}b=true}}f++}b&&this.diff_cleanupMerge(a)};
diff_match_patch.prototype.diff_cleanupMerge=function(a){a.push([0,""]);for(var b=0,c=0,d=0,e="",f="",g;b<a.length;)switch(a[b][0]){case 1:d++;f+=a[b][1];b++;break;case -1:c++;e+=a[b][1];b++;break;case 0:if(c+d>1){if(c!==0&&d!==0){g=this.diff_commonPrefix(f,e);if(g!==0){if(b-c-d>0&&a[b-c-d-1][0]==0)a[b-c-d-1][1]+=f.substring(0,g);else{a.splice(0,0,[0,f.substring(0,g)]);b++}f=f.substring(g);e=e.substring(g)}g=this.diff_commonSuffix(f,e);if(g!==0){a[b][1]=f.substring(f.length-g)+a[b][1];f=f.substring(0,
f.length-g);e=e.substring(0,e.length-g)}}if(c===0)a.splice(b-c-d,c+d,[1,f]);else d===0?a.splice(b-c-d,c+d,[-1,e]):a.splice(b-c-d,c+d,[-1,e],[1,f]);b=b-c-d+(c?1:0)+(d?1:0)+1}else if(b!==0&&a[b-1][0]==0){a[b-1][1]+=a[b][1];a.splice(b,1)}else b++;c=d=0;f=e=""}a[a.length-1][1]===""&&a.pop();c=false;for(b=1;b<a.length-1;){if(a[b-1][0]==0&&a[b+1][0]==0)if(a[b][1].substring(a[b][1].length-a[b-1][1].length)==a[b-1][1]){a[b][1]=a[b-1][1]+a[b][1].substring(0,a[b][1].length-a[b-1][1].length);a[b+1][1]=a[b-1][1]+
a[b+1][1];a.splice(b-1,1);c=true}else if(a[b][1].substring(0,a[b+1][1].length)==a[b+1][1]){a[b-1][1]+=a[b+1][1];a[b][1]=a[b][1].substring(a[b+1][1].length)+a[b+1][1];a.splice(b+1,1);c=true}b++}c&&this.diff_cleanupMerge(a)};diff_match_patch.prototype.diff_xIndex=function(a,b){var c=0,d=0,e=0,f=0,g;for(g=0;g<a.length;g++){if(a[g][0]!==1)c+=a[g][1].length;if(a[g][0]!==-1)d+=a[g][1].length;if(c>b)break;e=c;f=d}if(a.length!=g&&a[g][0]===-1)return f;return f+(b-e)};
diff_match_patch.prototype.diff_prettyHtml=function(a){for(var b=[],c=0,d=/&/g,e=/</g,f=/>/g,g=/\n/g,h=0;h<a.length;h++){var j=a[h][0],i=a[h][1],k=i.replace(d,"&amp;").replace(e,"&lt;").replace(f,"&gt;").replace(g,"&para;<BR>");switch(j){case 1:b[h]='<INS STYLE="background:#E6FFE6;" TITLE="i='+c+'">'+k+"</INS>";break;case -1:b[h]='<DEL STYLE="background:#FFE6E6;" TITLE="i='+c+'">'+k+"</DEL>";break;case 0:b[h]='<SPAN TITLE="i='+c+'">'+k+"</SPAN>"}if(j!==-1)c+=i.length}return b.join("")};
diff_match_patch.prototype.diff_text1=function(a){for(var b=[],c=0;c<a.length;c++)if(a[c][0]!==1)b[c]=a[c][1];return b.join("")};diff_match_patch.prototype.diff_text2=function(a){for(var b=[],c=0;c<a.length;c++)if(a[c][0]!==-1)b[c]=a[c][1];return b.join("")};diff_match_patch.prototype.diff_levenshtein=function(a){for(var b=0,c=0,d=0,e=0;e<a.length;e++){var f=a[e][0],g=a[e][1];switch(f){case 1:c+=g.length;break;case -1:d+=g.length;break;case 0:b+=Math.max(c,d);d=c=0}}b+=Math.max(c,d);return b};
diff_match_patch.prototype.diff_toDelta=function(a){for(var b=[],c=0;c<a.length;c++)switch(a[c][0]){case 1:b[c]="+"+encodeURI(a[c][1]);break;case -1:b[c]="-"+a[c][1].length;break;case 0:b[c]="="+a[c][1].length}return b.join("\t").replace(/%20/g," ")};
diff_match_patch.prototype.diff_fromDelta=function(a,b){for(var c=[],d=0,e=0,f=b.split(/\t/g),g=0;g<f.length;g++){var h=f[g].substring(1);switch(f[g].charAt(0)){case "+":try{c[d++]=[1,decodeURI(h)]}catch(j){throw Error("Illegal escape in diff_fromDelta: "+h);}break;case "-":case "=":var i=parseInt(h,10);if(isNaN(i)||i<0)throw Error("Invalid number in diff_fromDelta: "+h);h=a.substring(e,e+=i);if(f[g].charAt(0)=="=")c[d++]=[0,h];else c[d++]=[-1,h];break;default:if(f[g])throw Error("Invalid diff operation in diff_fromDelta: "+
f[g]);}}if(e!=a.length)throw Error("Delta length ("+e+") does not equal source text length ("+a.length+").");return c};diff_match_patch.prototype.match_main=function(a,b,c){if(a==null||b==null||c==null)throw Error("Null input. (match_main)");c=Math.max(0,Math.min(c,a.length));return a==b?0:a.length?a.substring(c,c+b.length)==b?c:this.match_bitap(a,b,c):-1};
diff_match_patch.prototype.match_bitap=function(a,b,c){function d(r,q){var p=r/b.length,t=Math.abs(c-q);if(!f.Match_Distance)return t?1:p;return p+t/f.Match_Distance}if(b.length>this.Match_MaxBits)throw Error("Pattern too long for this browser.");var e=this.match_alphabet(b),f=this,g=this.Match_Threshold,h=a.indexOf(b,c);if(h!=-1){g=Math.min(d(0,h),g);h=a.lastIndexOf(b,c+b.length);if(h!=-1)g=Math.min(d(0,h),g)}var j=1<<b.length-1;h=-1;for(var i,k,l=b.length+a.length,m,n=0;n<b.length;n++){i=0;for(k=
l;i<k;){if(d(n,c+k)<=g)i=k;else l=k;k=Math.floor((l-i)/2+i)}l=k;i=Math.max(1,c-k+1);var o=Math.min(c+k,a.length)+b.length;k=Array(o+2);k[o+1]=(1<<n)-1;for(o=o;o>=i;o--){var s=e[a.charAt(o-1)];k[o]=n===0?(k[o+1]<<1|1)&s:(k[o+1]<<1|1)&s|(m[o+1]|m[o])<<1|1|m[o+1];if(k[o]&j){s=d(n,o-1);if(s<=g){g=s;h=o-1;if(h>c)i=Math.max(1,2*c-h);else break}}}if(d(n+1,c)>g)break;m=k}return h};
diff_match_patch.prototype.match_alphabet=function(a){for(var b={},c=0;c<a.length;c++)b[a.charAt(c)]=0;for(c=0;c<a.length;c++)b[a.charAt(c)]|=1<<a.length-c-1;return b};
diff_match_patch.prototype.patch_addContext=function(a,b){if(b.length!=0){for(var c=b.substring(a.start2,a.start2+a.length1),d=0;b.indexOf(c)!=b.lastIndexOf(c)&&c.length<this.Match_MaxBits-this.Patch_Margin-this.Patch_Margin;){d+=this.Patch_Margin;c=b.substring(a.start2-d,a.start2+a.length1+d)}d+=this.Patch_Margin;(c=b.substring(a.start2-d,a.start2))&&a.diffs.unshift([0,c]);(d=b.substring(a.start2+a.length1,a.start2+a.length1+d))&&a.diffs.push([0,d]);a.start1-=c.length;a.start2-=c.length;a.length1+=
c.length+d.length;a.length2+=c.length+d.length}};
diff_match_patch.prototype.patch_make=function(a,b,c){var d;if(typeof a=="string"&&typeof b=="string"&&typeof c=="undefined"){d=a;b=this.diff_main(d,b,true);if(b.length>2){this.diff_cleanupSemantic(b);this.diff_cleanupEfficiency(b)}}else if(a&&typeof a=="object"&&typeof b=="undefined"&&typeof c=="undefined"){b=a;d=this.diff_text1(b)}else if(typeof a=="string"&&b&&typeof b=="object"&&typeof c=="undefined"){d=a;b=b}else if(typeof a=="string"&&typeof b=="string"&&c&&typeof c=="object"){d=a;b=c}else throw Error("Unknown call format to patch_make.");
if(b.length===0)return[];c=[];a=new patch_obj;var e=0,f=0,g=0,h=d;d=d;for(var j=0;j<b.length;j++){var i=b[j][0],k=b[j][1];if(!e&&i!==0){a.start1=f;a.start2=g}switch(i){case 1:a.diffs[e++]=b[j];a.length2+=k.length;d=d.substring(0,g)+k+d.substring(g);break;case -1:a.length1+=k.length;a.diffs[e++]=b[j];d=d.substring(0,g)+d.substring(g+k.length);break;case 0:if(k.length<=2*this.Patch_Margin&&e&&b.length!=j+1){a.diffs[e++]=b[j];a.length1+=k.length;a.length2+=k.length}else if(k.length>=2*this.Patch_Margin)if(e){this.patch_addContext(a,
h);c.push(a);a=new patch_obj;e=0;h=d;f=g}}if(i!==1)f+=k.length;if(i!==-1)g+=k.length}if(e){this.patch_addContext(a,h);c.push(a)}return c};diff_match_patch.prototype.patch_deepCopy=function(a){for(var b=[],c=0;c<a.length;c++){var d=a[c],e=new patch_obj;e.diffs=[];for(var f=0;f<d.diffs.length;f++)e.diffs[f]=d.diffs[f].slice();e.start1=d.start1;e.start2=d.start2;e.length1=d.length1;e.length2=d.length2;b[c]=e}return b};
diff_match_patch.prototype.patch_apply=function(a,b){if(a.length==0)return[b,[]];a=this.patch_deepCopy(a);var c=this.patch_addPadding(a);b=c+b+c;this.patch_splitMax(a);for(var d=0,e=[],f=0;f<a.length;f++){var g=a[f].start2+d,h=this.diff_text1(a[f].diffs),j,i=-1;if(h.length>this.Match_MaxBits){j=this.match_main(b,h.substring(0,this.Match_MaxBits),g);if(j!=-1){i=this.match_main(b,h.substring(h.length-this.Match_MaxBits),g+h.length-this.Match_MaxBits);if(i==-1||j>=i)j=-1}}else j=this.match_main(b,h,
g);if(j==-1){e[f]=false;d-=a[f].length2-a[f].length1}else{e[f]=true;d=j-g;g=i==-1?b.substring(j,j+h.length):b.substring(j,i+this.Match_MaxBits);if(h==g)b=b.substring(0,j)+this.diff_text2(a[f].diffs)+b.substring(j+h.length);else{g=this.diff_main(h,g,false);if(h.length>this.Match_MaxBits&&this.diff_levenshtein(g)/h.length>this.Patch_DeleteThreshold)e[f]=false;else{this.diff_cleanupSemanticLossless(g);h=0;var k;for(i=0;i<a[f].diffs.length;i++){var l=a[f].diffs[i];if(l[0]!==0)k=this.diff_xIndex(g,h);
if(l[0]===1)b=b.substring(0,j+k)+l[1]+b.substring(j+k);else if(l[0]===-1)b=b.substring(0,j+k)+b.substring(j+this.diff_xIndex(g,h+l[1].length));if(l[0]!==-1)h+=l[1].length}}}}}b=b.substring(c.length,b.length-c.length);return[b,e]};
diff_match_patch.prototype.patch_addPadding=function(a){for(var b=this.Patch_Margin,c="",d=1;d<=b;d++)c+=String.fromCharCode(d);for(d=0;d<a.length;d++){a[d].start1+=b;a[d].start2+=b}d=a[0];var e=d.diffs;if(e.length==0||e[0][0]!=0){e.unshift([0,c]);d.start1-=b;d.start2-=b;d.length1+=b;d.length2+=b}else if(b>e[0][1].length){var f=b-e[0][1].length;e[0][1]=c.substring(e[0][1].length)+e[0][1];d.start1-=f;d.start2-=f;d.length1+=f;d.length2+=f}d=a[a.length-1];e=d.diffs;if(e.length==0||e[e.length-1][0]!=
0){e.push([0,c]);d.length1+=b;d.length2+=b}else if(b>e[e.length-1][1].length){f=b-e[e.length-1][1].length;e[e.length-1][1]+=c.substring(0,f);d.length1+=f;d.length2+=f}return c};
diff_match_patch.prototype.patch_splitMax=function(a){for(var b=0;b<a.length;b++)if(a[b].length1>this.Match_MaxBits){var c=a[b];a.splice(b--,1);for(var d=this.Match_MaxBits,e=c.start1,f=c.start2,g="";c.diffs.length!==0;){var h=new patch_obj,j=true;h.start1=e-g.length;h.start2=f-g.length;if(g!==""){h.length1=h.length2=g.length;h.diffs.push([0,g])}for(;c.diffs.length!==0&&h.length1<d-this.Patch_Margin;){g=c.diffs[0][0];var i=c.diffs[0][1];if(g===1){h.length2+=i.length;f+=i.length;h.diffs.push(c.diffs.shift());
j=false}else if(g===-1&&h.diffs.length==1&&h.diffs[0][0]==0&&i.length>2*d){h.length1+=i.length;e+=i.length;j=false;h.diffs.push([g,i]);c.diffs.shift()}else{i=i.substring(0,d-h.length1-this.Patch_Margin);h.length1+=i.length;e+=i.length;if(g===0){h.length2+=i.length;f+=i.length}else j=false;h.diffs.push([g,i]);if(i==c.diffs[0][1])c.diffs.shift();else c.diffs[0][1]=c.diffs[0][1].substring(i.length)}}g=this.diff_text2(h.diffs);g=g.substring(g.length-this.Patch_Margin);i=this.diff_text1(c.diffs).substring(0,
this.Patch_Margin);if(i!==""){h.length1+=i.length;h.length2+=i.length;if(h.diffs.length!==0&&h.diffs[h.diffs.length-1][0]===0)h.diffs[h.diffs.length-1][1]+=i;else h.diffs.push([0,i])}j||a.splice(++b,0,h)}}};diff_match_patch.prototype.patch_toText=function(a){for(var b=[],c=0;c<a.length;c++)b[c]=a[c];return b.join("")};
diff_match_patch.prototype.patch_fromText=function(a){var b=[];if(!a)return b;a=a.split("\n");for(var c=0,d=/^@@ -(\d+),?(\d*) \+(\d+),?(\d*) @@$/;c<a.length;){var e=a[c].match(d);if(!e)throw Error("Invalid patch string: "+a[c]);var f=new patch_obj;b.push(f);f.start1=parseInt(e[1],10);if(e[2]===""){f.start1--;f.length1=1}else if(e[2]=="0")f.length1=0;else{f.start1--;f.length1=parseInt(e[2],10)}f.start2=parseInt(e[3],10);if(e[4]===""){f.start2--;f.length2=1}else if(e[4]=="0")f.length2=0;else{f.start2--;
f.length2=parseInt(e[4],10)}for(c++;c<a.length;){e=a[c].charAt(0);try{var g=decodeURI(a[c].substring(1))}catch(h){throw Error("Illegal escape in patch_fromText: "+g);}if(e=="-")f.diffs.push([-1,g]);else if(e=="+")f.diffs.push([1,g]);else if(e==" ")f.diffs.push([0,g]);else if(e=="@")break;else if(e!=="")throw Error('Invalid patch mode "'+e+'" in: '+g);c++}}return b};function patch_obj(){this.diffs=[];this.start2=this.start1=null;this.length2=this.length1=0}
patch_obj.prototype.toString=function(){var a,b;a=this.length1===0?this.start1+",0":this.length1==1?this.start1+1:this.start1+1+","+this.length1;b=this.length2===0?this.start2+",0":this.length2==1?this.start2+1:this.start2+1+","+this.length2;a=["@@ -"+a+" +"+b+" @@\n"];var c;for(b=0;b<this.diffs.length;b++){switch(this.diffs[b][0]){case 1:c="+";break;case -1:c="-";break;case 0:c=" "}a[b+1]=c+encodeURI(this.diffs[b][1])+"\n"}return a.join("").replace(/%20/g," ")};window.diff_match_patch=diff_match_patch;
window.patch_obj=patch_obj;window.DIFF_DELETE=-1;window.DIFF_INSERT=1;window.DIFF_EQUAL=0;})()
